### PR TITLE
Synchronizing Layouts and Plugins with CMSSW development

### PR DESCRIPTION
**Pull request by vkhristenko**
This is 2nd iteration of updates of Layouts/Plugins for HCAL. It synchronizes dev with CMSSW devs.

Updated:
1) Plugins
-- color scheme - simple integer

2) Layouts
So, I know this is not the preferred way of doing things - but it's the most efficient way for HCAL DQM to function. Layouts are generated based on the ROOT file generated by the CMSSW. Therefore, layouts are quite long....

Updated layouts:
1) hcal workspace layouts for both online/offline
2) shift -> hcal workspace layouts for both online/offline
3) hcalcalib and shift hcalcalib layouts for online were updated.

VK

### CODE REVIEW

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo
Tests OK.
Can you merge this?
Thanks

**Comment by vkhristenko** [comment]
adding a commit...

**Comment by vkhristenko** [comment]
that was the last commit... if was neccessary to sync with CMSSW devs

VK

**Comment by BrunoCoimbra** [comment]
Hi @vanbesien and @vkhristenko, do we need new tests after the latests commits?

**Comment by vkhristenko** [comment]
@BrunoCoimbra let's leave as is for today - starting tomorrow it should be ok!


VK

**Comment by vanbesien** [comment]
@BrunoCoimbra
New tests OK.
This can be merged.

Thanks

**Pull request closed without merging**
