### PR TITLE
AMQ monitoring fixes for T0 WMAgent configuration

### PR DESCRIPTION
**Pull request by vytjan**
Reading AMQ credentials from secrets file.

### CODE REVIEW

**Comment by amaltaro** [comment]
Looks good!

**Comment by vytjan** [comment]
@amaltaro Alan, are you able to merge this PR? Or should I ask someone else to do that?

**Comment by amaltaro** [comment]
@h4d4 Lina is the person merging stuff into this repo.

**Comment by h4d4** [comment]
@vytjan @amaltaro Alan, Vytas,

one question, are those configuration's changes needed to be deployed on testbed?
for when have you planned to put it in production?

Best Regards, Lina.

**Comment by amaltaro** [comment]
No Lina, this only affects the T0 WMAgent which is not deployed in cmsweb. You can safely merge it

**Comment by h4d4** [comment]
@vytjan @amaltaro 

ok, merged.

Best Regards, Lina.

**Pull request merged**
