### PR TITLE
Render plugin update for Pixel Quality plots from PCL

### PR DESCRIPTION
**Pull request by tocheng**
Hello,
the PR is to apply pixel map render plugin to Pixel Quality plots from PCL.
I don't add the plots to Layouts because they will be empty for "standard" DQM plots (Express/Prompt).
I tested it with a private offline DQM GUI using the DQM IO from CMSSW_10_2_0 replay
image

### CODE REVIEW

**Comment by threus** [comment]
@tocheng you mention you don't add plots to the layouts, yet you modify the online Pixel layout. Can you explain/confirm this is your intention? Thank you

**Comment by tocheng** [comment]
@threus  Thanks for point it out! I just want to apply the render plugin. There is no need to add the plots to pixel layout. I have reverted the commit. So now the PR is only for render plugin update.

**Comment by tocheng** [comment]
@threus Hello, could you please test and merge the PR asap? We would like the offline shifters to look at the plots. Thanks!

**Comment by threus** [comment]
@h4d4 , Tests are OK. Could you please merge this?
Thanks,
Tomas for DQM

**Pull request merged**
