### PR TITLE
Add silence before placing maintenance alert

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , based on discussion in https://its.cern.ch/jira/browse/CMSMONIT-229 I added silence in front of maintenance alert. So far I put 2h of duration and didn't capture silence ID, but we may adjust it later. Please review and we may try it next time you'll do the maintenance.

My understanding that you still got emails about outages of all services after I changed AM routes, rights?

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Yes, I still got emails during outage today.

**Comment by vkuznet** [comment]
I don't mind to remove your email from AM, but that will defeat the purpose of this PR and other efforts. Let's try silence approach and see next time how it will go.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I performed the following tests:
* add silence for 5 minutes with cmsweb tag
```
amtool silence add --duration=5m --comment "test cmsweb maintenance silence" tag=cmsweb --alertmanager.url=<url>
```
* set small expire interval for upcoming alert, e.g. 2m
```
expire=`date -d '+2 minute' --rfc-3339=ns | tr ' ' 'T'`
```
* set das test alert with aforementioned expire
```
amtool alert add test_das_maintenance severity=medium service=das tag=cmsweb --end=$expire --alertmanager.url=<url>--annotation=date='`date`'
```
Then I checked alerts in AM, and I found that my DAS alert was Silenced and then it disappeared (after its expire). During this time I didn't get notification neither in email or in Slack.

Therefore, this procedure seems to work. Please merge and if necessary adjust silence interval, may be we should make it optional (it is up to you).

**Comment by vkuznet** [comment]
And, so far I didn't capture SILENCE ID but we can if you want to and we may use it when you finish maintenance and then issue again amtool to expire given SILENCE ID.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

In collectd, I don't disable alarms for specific time intervial. Infact, I disable them and re-enable alarms after intervention. In this way, using SILENCE ID would be fine instead of declaring time intervals.

**Pull request merged**
