### PR TITLE
remove wmbsservice

### PR DESCRIPTION
**Pull request by ticoann**
@amaltaro, @hufnagel, Alan, Dirk if you use agent newer than 1.1.2.pre3. This deployment script is needed. You can also remove WMBS_SERVICE_PORT from secrete file.

### CODE REVIEW

**Comment by ticoann** [comment]
@amaltaro, @hufnagel Alan, it this looks OK, could you merge this?

**Comment by amaltaro** [comment]
Seangchan, it looks good for me and I've been using it since the last week.
@hufnagel do you clone the deployment repo for each T0 agent deployment? If that's the case, then we may need to wait until you move to a newer WMCore version, then we can merge it.

**Comment by hufnagel** [comment]
Yes, we clone the deployment repo during T0 deployment. The head will stop working without the corresponding WMCore changes ? We already do disable WMBSService ourselves in the latest Tier0 version.

**Comment by hufnagel** [comment]
Easier is if you just point us at the patch for WMCore we will need (commit id after merge is preferred), we can then add it to the T0 release twiki.

**Comment by ticoann** [comment]
Hi Dirk, what is current Tier0 version (WMCore version T0 is using). In stead of patching T0, we can merge later when T0 is using newer than 1.1.2.pre3 WMCore

**Comment by hufnagel** [comment]
We use WMCore 1.1.0.pre6. Really, if you can tell us what commit to use on top of that to be compatible with the new deployment code, we can just add that to the T0 release twiki. I was planning to build a new T0 release with newer WMCore code, but not very urgently.

**Comment by ticoann** [comment]
Hi Dirk, this is the patch. I am not sure this will be cleanly applied to 1.1.0.pre6. If not I can create a new patch.
https://github.com/dmwm/WMCore/pull/7735

**Comment by hufnagel** [comment]
Patch applies clean to a Tier0 deployment. Can the patch be used without the corresponding deployment changes or do we need to sync this ?

**Comment by ticoann** [comment]
we need to sync this.

**Comment by amaltaro** [comment]
Dirk, are you all set on the T0 side? Can we merge it now?

**Comment by hufnagel** [comment]
Just merge it and let me know, I'll update the T0 release twiki then.

**Comment by amaltaro** [comment]
@BrunoCoimbra @h4d4 can you merge it please? Thanks

**Pull request merged**
