### PR TITLE
Changed redirection rules for the new DQM GUI

### PR DESCRIPTION
**Pull request by andrius-k**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Could you please review this. Are changes according to your comments in the email?

**Comment by vkuznet** [comment]
+1, but as I wrote I rather want to see confirmation from @andrius-k  about the tests of this rule.

**Comment by andrius-k** [comment]
@vkuznet I made this PR as a test to see if the redirections behave as expected. As I understand, the cmsweb-testX clusters are based on Kubernetes and the new GUI doesn't support that yet.

**Comment by vkuznet** [comment]
My point was that you can login to cmsweb-testX cluster and manually change FE config, then restart it to test the rules. It will be more efficient since you'll test everything before putting untested rule in our FE config. If you can't do it, it is fine and we can merge to proceed with testing.

**Comment by andrius-k** [comment]
Pardon my ignorance, I'm not familiar with this process. Is there some documentation on how to login to the test cluster, which file to edit for changing the rules, how to restart and how to access the new updated FE?

**Comment by vkuznet** [comment]
Ahh, I miss the point that now FE runs as daemonsets and because of that we can't easily modify them on cmsweb-testX cluster. SO, let's proceed with adding rule and redeploying it on one of the test cluster. @muhammadimranfarooqi  should help you with that.

**Comment by andrius-k** [comment]
@vkuznet We have deployed this change but now, ALL requests get redirected to `/` in the service. In other words,
`https://cmsweb-testbed.cern.ch/dqm/offline-test-new/` goes to `/` and 
`https://cmsweb-testbed.cern.ch/dqm/offline-test-new/images/logo.png` goes to `/` as well.
What we'd like to have is this:
`https://cmsweb-testbed.cern.ch/dqm/offline-test-new/` -> `/`
`https://cmsweb-testbed.cern.ch/dqm/offline-test-new/images/logo.png` -> `/images/logo.png`
Do you have a suggestion on how to configure these redirections?

**Comment by vkuznet** [comment]
Andrius, that's why I suggested to test first all the rules. In this case you need a series of them. I just tested a few patterns using httpgo service and cmsweb-test6 cluster. Here are the rules:
```
  RewriteRule ^(/httpgo(/.*)?)$ /auth/verify${escape:$1} [QSA,PT,E=AUTH_SPEC:cert]
  RewriteRule ^/auth/complete/httpgo(/bla(/.*)?)$ http://localhost:8888${escape:$1} [QSA,P,L,NE]
  RewriteRule ^/auth/complete/httpgo/ http://localhost:8888 [QSA,P,L,NE]
```
And I can place requests like:
```
# redirect to / in httpgo localhost
curl <options> https://cmsweb-test6.cern.ch/httpgo/  

# redirect to /bla?a=1 in httpgo localhost
curl <options> https://cmsweb-test6.cern.ch/httpgo/bla?a=1
```

Therefore, you need a series of **explicit** rules for all your paths in your service ( like /images) and last rule for everything which should be redirected to `/`.

Please make adjustements to rules in new PR.

I adjusted cmsweb-test6 cluster to use FE as a service (not daemon set) and you can try it out. Here is a procedure:
```
# login to lxplus-cloud

# setup proper KUBECONFIG to access this cluster
export KUBECONFIG=/afs/cern.ch/user/m/mimran/public/cmsweb-k8s/config.cmsweb-test6

# login to FE pod
kubectl exec -ti frontend-55b8dffd78-cr5bv -- /bin/bash

# adjust FE config
vi /data/srv/state/frontend/server.conf

# restart FE
/data/cfg/admin/InstallDev -s start
```
Then from another terminal you can test your service via curl. I test httpgo service. But you can add to FE your DQM stuff and point to proper host:port.

**Comment by andrius-k** [comment]
Hi @vkuznet, it seems that I'm getting an error logging in to the FE pod. Listing the pods doesn't return the pod `frontend-55b8dffd78-cr5bv`. Am I doing something wrong?

``` bash
[akirilov@lxplus725.cern.ch ~ [10] 14:59:23]$ export KUBECONFIG=/afs/cern.ch/user/m/mimran/public/cmsweb-k8s/config.cmsweb-test6
[akirilov@lxplus725.cern.ch ~ [10] 14:59:30]$ kubectl exec -ti frontend-55b8dffd78-cr5bv -- /bin/bash
Error from server (NotFound): pods "frontend-55b8dffd78-cr5bv" not found
[akirilov@lxplus725.cern.ch ~ [10] 14:59:36]$ kubectl get pods
NAME                          READY   STATUS      RESTARTS   AGE
cron-proxy-1612483500-rp96d   0/1     Completed   0          13h
cron-proxy-1612505100-jxq88   0/1     Completed   0          7h54m
cron-proxy-1612526700-2jn4w   0/1     Completed   0          114m
```

**Comment by muhammadimranfarooqi** [comment]
Hi @andrius-k 

Actually I have updated FEs yesterday with daemonset. You may provide new PR for desired changes and I'll deploy it on testbed.

**Comment by andrius-k** [comment]
Hi @muhammadimranfarooqi,
I don't have the rewrite rules yet. I'd like to connect to the test pod to write and debug the rules for redirections.

**Comment by vkuznet** [comment]
Ahh, you're late :) it seems Muhammad is already updated testX cluster and now it is back to use daemonset. The FE daemonset run in `auth` namespace. So, do this instead:
```
# list pods in auth namespace
kubectl -n auth get pod

# login to FE in auth namespace
kubectl -n auth exec -ti frontend-g98qd -- /bin/bash
```

**Comment by vkuznet** [comment]
it would be better to test rules first within running FE. Doing this way we don't need to iterate PRs each time and let Andrius to adjust rules as he desire.

**Comment by muhammadimranfarooqi** [comment]
I am deploying again with frontend as services.

**Comment by andrius-k** [comment]
@vkuznet, now running the following and the pod still seems to be not found:

``` bash
[akirilov@lxplus765.cern.ch ~ [10] 15:15:07]$ export KUBECONFIG=/afs/cern.ch/user/m/mimran/public/cmsweb-k8s/config.cmsweb-test6
[akirilov@lxplus765.cern.ch ~ [10] 15:15:22]$ kubectl -n auth get pod
NAME                          READY   STATUS      RESTARTS   AGE
cron-proxy-1612483500-srqmh   0/1     Completed   0          14h
cron-proxy-1612505100-h8djz   0/1     Completed   0          8h
cron-proxy-1612526700-2qqxh   0/1     Completed   0          130m
[akirilov@lxplus765.cern.ch ~ [10] 15:15:32]$ kubectl -n auth exec -ti frontend-g98qd -- /bin/bash
Error from server (NotFound): pods "frontend-g98qd" not found
```

**Comment by muhammadimranfarooqi** [comment]
```
[mimran@lxplus725]~/ kubectl get pods
NAME                          READY   STATUS      RESTARTS   AGE
cron-proxy-1612483500-rp96d   0/1     Completed   0          14h
cron-proxy-1612505100-jxq88   0/1     Completed   0          8h
cron-proxy-1612526700-2jn4w   0/1     Completed   0          131m
frontend-78658b9ddc-wcbbm     1/1     Running     0          3m9s
[mimran@lxplus725]~/% kubectl exec -it frontend-78658b9ddc-wcbbm bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.

**Comment by andrius-k** [comment]
@muhammadimranfarooqi works, thanks!

**Comment by muhammadimranfarooqi** [comment]
@andrius-k 

After changes in `/data/srv/state/frontend/server.conf` file, you need to restart FE service. Like this https://cms-http-group.docs.cern.ch/vm_cluster/services_procedures/#aparche-frontent-service

**Comment by andrius-k** [comment]
@muhammadimranfarooqi Thanks!
Final question: how can I access the FE running on this pod from the outside. `https://cmsweb-test6.cern.ch/` doesn't seem to return. Accessing from the same pod works, but I don't get past the authentication.

**Comment by vkuznet** [comment]
WHat do you mean outside? Outside of CERN network or not? If you need to access from outside of CERN network learn how to use ssh or SOCK tunnels in your browser. If you need help with that I can send some info. If you mean that you can't access your service it means that something wrong with your rules. 

But it seems to me that the problem is with FE itself since I see this:
```
scurl -v https://cmsweb-test6.cern.ch/
* About to connect() to cmsweb-test6.cern.ch port 443 (#0)
*   Trying 188.185.91.18...
* Connection refused
*   Trying 188.185.86.130...
* Connection refused
*   Trying 188.185.86.180...
* Connection refused
* Failed connect to cmsweb-test6.cern.ch:443; Connection refused
* Closing connection 0
curl: (7) Failed connect to cmsweb-test6.cern.ch:443; Connection refused
```

@muhammadimranfarooqi did you setup ingress controller (and label nodes to allow to start it)? Please do and check that FE is accessible.

**Comment by muhammadimranfarooqi** [comment]
The URL `https://cmsweb-test6.cern.ch/` will be accessible from the CERN network only as its firewall not opened.  Try now

**Comment by muhammadimranfarooqi** [comment]
Yes, I have setup ingress. now working.

**Comment by andrius-k** [comment]
When I go from CERN network, I get a certificate error. Do you have a goto way to deal with these things?

**Comment by muhammadimranfarooqi** [comment]
you need certificate to get authenticated from CMSWEB FE. 

```
[mimran@lxplus725]~% curl -k -v --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem https://cmsweb-test6.cern.ch
* About to connect() to cmsweb-test6.cern.ch port 443 (#0)
*   Trying 188.185.91.18...
* Connected to cmsweb-test6.cern.ch (188.185.91.18) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
*       subject: CN=Muhammad Imran,CN=709989,CN=mimran,OU=Users,OU=Organic Units,DC=cern,DC=ch
*       start date: Oct 13 10:33:02 2020 GMT
*       expire date: Nov 17 10:33:02 2021 GMT
*       common name: Muhammad Imran
*       issuer: CN=CERN Grid Certification Authority,DC=cern,DC=ch
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=cmsweb-test6.cern.ch,OU=computers,DC=cern,DC=ch
*       start date: Apr 03 11:43:43 2020 GMT
*       expire date: May 08 11:43:43 2021 GMT
*       common name: cmsweb-test6.cern.ch
*       issuer: CN=CERN Grid Certification Authority,DC=cern,DC=ch
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cmsweb-test6.cern.ch
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 05 Feb 2021 15:20:10 GMT
< Server: Apache
< Last-Modified: Fri, 05 Feb 2021 14:57:18 GMT
< ETag: "a9d-5ba9809572975"
< Accept-Ranges: bytes
< Content-Length: 2717
< CMS-Server-Time: D=31673 t=1612538410599270
< Content-Type: text/html
<
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>CMS WEB TOOLS Index Page</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" media="screen" href="css/cmsweb.css" />
  </head>

  <body>
    <div id="main">
    <div id="top">
      <div class="boxTitle"><img src="img/title.gif" alt="CMSWEB (title)" /></div>
    </div>
    <div id="middle">
      <div class="boxLinkContainer">
        <ul class="boxLinks">
          <li class="box">Data catalogue: <a href="/das/">DAS</a></li>
          <li class="box">Transfer systems:
            <a href="/phedex/">PhEDEx - bulk transfer</a>
          </li>
          <li class="box">Workflow monitoring:
            <a href="https://monit-grafana.cern.ch/d/000000530/cms-monitoring-project?orgId=11">Dashboard</a>,
            <a href="/reqmgr2/">Request Manager 2</a>,
            <a href="/wmstats/index.html">Request Monitor</a>,
            <a href="/workqueue/index.html">Work Queue</a>,
            <a href="/crabserver/ui">CRAB3 Monitor</a>,
            <a href="http://cms-gwmsmon.cern.ch">Global pool Monitor</a>
          </li>
          <li class="box">DQM:
            <a href="/dqm/online/">Online</a>,
            <a href="/dqm/online-new">Online-new</a>,
            <a href="/dqm/online-playback/">Online-playback</a>,
            <a href="/dqm/online-playback-new">Online-playback-new</a>,
            <a href="/dqm/online-test/">Online-test</a>,
            <a href="/dqm/online-test-new">Online-test-new</a>,
            <a href="/dqm/offline/">Offline</a>,
            <a href="/dqm/offline-new/">Offline-new</a>,
            <a href="/dqm/offline-test-new/">Offline-test-new</a>,
            <a href="/dqm/relval/">RelVal</a>,
            <a href="/dqm/relval-new/">RelVal-new</a>,
            <a href="/dqm/relval-test-new/">Relval-test-new</a>,
            <a href="/dqm/dev/">Development</a>
          </li>
          <li class="box">Site systems:
             <a href="https://hammercloud.cern.ch/hc/app/cms/">HammerCloud</a>,
             <a href="https://gitlab.cern.ch/groups/SITECONF">SITECONF</a>
          </li>
          <li class="box"><a href="https://cms-cric.cern.ch/">CMS CRIC system</a></li>
          <li class="box"><a href="/exitcodes/">CMS Exit Codes</a></li>
          <li class="box"><a href="/help.html">Help and support</a></li>
        </ul>
      </div>
    </div>
    <div id="bottom"><div class="boxFooter">&nbsp;</div></div>
    </div>
  </body>

</html>
* Connection #0 to host cmsweb-test6.cern.ch left intact
```

**Comment by andrius-k** [comment]
I set up the certificates and I can access the old GUI fine:
```
curl -k -v --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem https://cmsweb-test6.cern.ch/dqm/offline-test/
```

However, the new one returns an error:
``` bash
[akirilov@lxplus765.cern.ch ~ [10] 16:38:04]$ curl -k -v --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem https://cmsweb-test6.cern.ch/dqm/offline-test-new/
* About to connect() to cmsweb-test6.cern.ch port 443 (#0)
*   Trying 188.185.86.130...
* Connected to cmsweb-test6.cern.ch (188.185.86.130) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
* 	subject: CN=Andrius Kirilovas,CN=827113,CN=akirilov,OU=Users,OU=Organic Units,DC=cern,DC=ch
* 	start date: Feb 05 15:20:04 2021 GMT
* 	expire date: Mar 12 15:20:04 2022 GMT
* 	common name: Andrius Kirilovas
* 	issuer: CN=CERN Grid Certification Authority,DC=cern,DC=ch
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=cmsweb-test6.cern.ch,OU=computers,DC=cern,DC=ch
* 	start date: Apr 03 11:43:43 2020 GMT
* 	expire date: May 08 11:43:43 2021 GMT
* 	common name: cmsweb-test6.cern.ch
* 	issuer: CN=CERN Grid Certification Authority,DC=cern,DC=ch
> GET /dqm/offline-test-new/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cmsweb-test6.cern.ch
> Accept: */*
>
< HTTP/1.1 502 Proxy Error
< Date: Fri, 05 Feb 2021 15:38:53 GMT
< Server: Apache
< Set-Cookie: cms-auth=2af38512595245bc8355c03464c3db3f84d510729eef5d7babab39d096bf3311c1df7698018e3b19;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT
< Content-Length: 459
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/auth/complete/dqm/offline-test-new/">GET&nbsp;/auth/complete/dqm/offline-test-new/</a></em>.<p>
Reason: <strong>DNS lookup failure for: cmsweb-srv.cern.ch</strong></p></p>
</body></html>
* Connection #0 to host cmsweb-test6.cern.ch left intact
```

**Comment by muhammadimranfarooqi** [comment]
Try now
```
[mimran@lxplus725]~% curl -k -v --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem https://cmsweb-test6.cern.ch/dqm/offline-test/
* About to connect() to cmsweb-test6.cern.ch port 443 (#0)
*   Trying 188.185.86.130...
* Connected to cmsweb-test6.cern.ch (188.185.86.130) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
*       subject: CN=Muhammad Imran,CN=709989,CN=mimran,OU=Users,OU=Organic Units,DC=cern,DC=ch
*       start date: Oct 13 10:33:02 2020 GMT
*       expire date: Nov 17 10:33:02 2021 GMT
*       common name: Muhammad Imran
*       issuer: CN=CERN Grid Certification Authority,DC=cern,DC=ch
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=cmsweb-test6.cern.ch,OU=computers,DC=cern,DC=ch
*       start date: Apr 03 11:43:43 2020 GMT
*       expire date: May 08 11:43:43 2021 GMT
*       common name: cmsweb-test6.cern.ch
*       issuer: CN=CERN Grid Certification Authority,DC=cern,DC=ch
> GET /dqm/offline-test/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cmsweb-test6.cern.ch
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 05 Feb 2021 15:46:04 GMT
< Server: CherryPy/5.4.0
< Set-Cookie: cms-auth=5484eae2374527da5a9ace8cdf48cae00fee003712f355553f220a43d6e259a49f31772d0ed7ed48;path=/;secure;httponly;expires=Thu, 01-Jan-1970 00:00:01 GMT
< Content-Length: 173
< Content-Type: text/html;charset=utf-8
< CMS-Server-Time: D=119424 t=1612539964049922
<
* Connection #0 to host cmsweb-test6.cern.ch left intact
<html><head><script>location.replace('/dqm/offline-test/session/GmJ3DZ')</script></head><body><noscript>Please enable JavaScript to use this service</noscript></body></html>%

**Comment by andrius-k** [comment]
I see in this comment you access the old GUI (https://cmsweb-test6.cern.ch/dqm/offline-test/) which works fine. However, the new one (https://cmsweb-test6.cern.ch/dqm/offline-test-new/) still gives the error I posted above.

**Comment by muhammadimranfarooqi** [comment]
now?

**Comment by andrius-k** [comment]
Works! Perfect, thanks!

**Comment by andrius-k** [comment]
@muhammadimranfarooqi @vkuznet,
Looks like capturing everything after /dqm/*/ in a 3rd capture group and using it in redirection does the trick. The PR is here: https://github.com/dmwm/deployment/pull/1029

**Pull request merged**
