### PR TITLE
Adding wmarchive services to CMSWEB

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Review by vkuznet — CHANGES_REQUESTED** [review]
Muhammad, please remove immediately config, it contains the password !!! Never ever store anything with password to PUBLIC repository.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

I have removed. Now is it ready to deploy now?

**Comment by vkuznet** [comment]
@amaltaro please review the changes. We'll apply this to testbed and deploy WMArchive over there. It means that at some point it will be interruption on WMAgents which send data to testbed. And, due to incident on this ticket it would be another set of interruption once I'll apply new credentials.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , from my side everything now looks fine, please wait for Alan's confirmation.

**Comment by klannon** [comment]
Is this something that @goughes or @khurtado could review?  Alan need to focus on completing Rucio support in the WM software or we'll miss the deadline.

**Comment by vkuznet** [comment]
Kevin, there is no really much to review, we only redirect WMArchvie from vocms0181 (dedicated VM) to cmsweb BE (vocms0731 and vocms0741).

**Comment by amaltaro** [comment]
Since the passwd thing drew my attention here. I had a quick look and it's good to go from my side. I assume changes are going to be transparent as well, right? (Kevin, thanks for having my back!)

**Pull request merged**
