### PR TITLE
Sadia 2017

### PR DESCRIPTION
**Pull request by skhalil**
Extending Layouts for PixelPhase1 and updating the QuickCollections Online and Offline. Files edited are: pixelPhase1-layouts.py, pixelPhase1_T0_layouts.py, workspaces-online.py, workspaces-offline.py

### CODE REVIEW

**Comment by threus** [comment]
@BrunoCoimbra @h4d4 could you please merge this PR?
Thanks,
Tomas for DQM

**Comment by skhalil** [comment]
Apologies, but I found a bug in one histogram path that I was not able to test since it was not available earlier in CMSSW_9_0_0_pre5 in DQM software. I have made corrections to my branch. Shall I send another PR?

**Comment by vanbesien** [comment]
It's already merged
So you should pull the code, and make a new PR on top of what is the current master

**Comment by skhalil** [comment]
I did it yesterday, but now Francesco suggest to change the title of the plots as well. If https://github.com/dmwm/deployment/pull/457/files is not merged, then I would like to send one more PL.

**Comment by skhalil** [comment]
PR 457 was closed, and new PR https://github.com/dmwm/deployment/pull/461 has been created. Apologies for inconvenience.

**Pull request merged**
