### PR TITLE
Add ms-pileup-tasks

### PR DESCRIPTION
**Pull request by vkuznet**
It is up to Alan to decide if it is needed, see discussion in https://github.com/dmwm/WMCore/pull/11504

### CODE REVIEW

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , @arooshap , if @amaltaro agree please merge these changes, rebuild FE image and deploy to k8s cluster.

**Comment by amaltaro** [comment]
@vkuznet Valentin, can you please also provide the required changes to NGInx in:
https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/ingress/ing-dmwm.yaml#L83

and link the PR here? Once we get it all in, then a new FE image can be created.

**Comment by vkuznet** [comment]
Here is PR for ingress https://github.com/dmwm/CMSKubernetes/pull/1324 but it is not required for FE image creation per-se, it is deployment part which has nothing to do with FE image.

**Comment by amaltaro** [comment]
These changes look good to me.

Aroosha/Imran, please proceed with merge and new images at your convenience. Thanks!

**Comment by arooshap** [comment]
Hi @vkuznet and @amaltaro, I deployed frontends with the latest tag `HG2303a` in the testbed cluster.

**Pull request merged**
