### PR TITLE
Update address of Tracks and Vertex comparison in pixelHeterogenous-layouts

### PR DESCRIPTION
**Pull request by mmusich**
Fix needed to comply with naming changes. Due to this many plots are shown as not available.

Screenshot from 2024-05-13 09-56-58

### CODE REVIEW

**Comment by nothingface0** [comment]
Hey Marco, does this depend on any CMSSW PR which is not yet in 14_0_6 ?

**Comment by mmusich** [comment]
> Hey Marco, does this depend on any CMSSW PR which is not yet in 14_0_6 ?

no.

**Comment by nothingface0** [comment]
Everything looks fine from the online playback tests. Thanks Marco!

**Comment by arooshap** [comment]
Hi @mmusich @nothingface0,

Changes incorporated in HG2404a!

**Comment by nothingface0** [comment]
@mmusich It should already be deployed but there was some mixup. It's back up.

**Comment by mmusich** [comment]
> It should already be deployed but there was some mixup. It's back up.

Thank you @nothingface0, I confirm it's fine now.

**Pull request merged**
