### PR TITLE
WIP: uses robot cert to query cric

### PR DESCRIPTION
**Pull request by Panos512**
OK, this should be it to securely query CRIC.
I changed config to point to cms-cric-preprod. Once we make sure that this works in the testbed I can switch it back to use cric production and then we can merge it.

### CODE REVIEW

**Comment by yuyiguo** [comment]
@Panos512 

Are you going to tag this commit before we can test it? For my VM,  what is it a good choice:  robot or something else?

**Comment by Panos512** [comment]
Hi Yuyi, I'm not sure what tags to add.
Once @muhammadimranfarooqi  tests that this works on the testbed we should merge it.
I would suggest a robot certificate. Proxy certificate can also work but I have only tested it with a robot one.

This is the snippet I use:
```
url = 'http://cms-cric-preprod.cern.ch/api/accounts/user/query/?json&preset=roles'
cert = ('/path/to/robotcert.pem', '/path/to/robotkey.pem')
result = requests.get(url, cert=cert)
```

**Comment by muhammadimranfarooqi** [comment]
Hi @yuyiguo 

The tag for this PR is `HG2108b`.

**Comment by yuyiguo** [comment]
Hi @Panos512 @muhammadimranfarooqi 

I rebuilt DBS 3.16.0 with HG2108d and deployed the server and FE using HG2108d. I ran dbs tests and everything was fine.  I checked that FE was pointed to  cms-cric-preprod.cern.ch. Panos, can you check if the certificate used by dbs3-test2 stratified CRIC requirements?

I also tested against cmsweb-testbed and everything was fine too. Imran, Could you let me know which dbs server the current cmsweb-testbed connected to?  Are you still alternating between k8s and vm? I assumed that cmsweb-testbed FE already connected to  cms-cric-preprod.cern.ch?

**Comment by yuyiguo** [comment]
Hi @Panos512 @muhammadimranfarooqi

Can you check and reply?

**Comment by muhammadimranfarooqi** [comment]
@yuyiguo 

The frontend in testbed points to DBS from k8s testbed only. The version of DBS is same 3.16.0. Today I have deployed a new tag `HG2108e` that fixes an error in frontend for cric changes.

**Comment by yuyiguo** [comment]
@muhammadimranfarooqi 

I deployed with HG2108d on my testbed and did not have any problem. Can you be more specific on "that fixes an error in frontend for cric changes."?

**Comment by Panos512** [comment]
Hi Yuyi,

There were some errors with the certificate validation (needed to specify the CA files path), now everything should work OK.
If your certificate is in this list: https://cms-cric.cern.ch/accounts/account/list/ then it should be ok. All CMS certificates can be used to query CRIC.

Let me know if I can help more

**Comment by yuyiguo** [comment]
Hi @Panos512 ,

I redeployed DBS on my VM using HG2108e. This time the migration was failed. So I created /etc/robots/robotcert.pem and /ect/robots/robotkey.pem with my own cert.  Is it ok with you  ?  Another question is where is the json files generated by mkauthmap? I'd like to check if my system get them right.

Thanks,
Yuyi

**Comment by Panos512** [comment]
Hi @yuyiguo , yes your personal certificate should work, thanks! 

the default location for the output of `mkauthmap` is `/data/srv/state/frontend/etc/authmap.json`

Cheers,
Panos

**Comment by yuyiguo** [comment]
Hi @Panos512 ,

I did not find authmap.json in my system. I am wondering how it worked?
```
[dbs3-test2 ~ 1000] cd /data/srv
[dbs3-test2 srv 1001] find . -name authmap.json
[dbs3-test2 srv 1002] find . -name voms-gridmap.txt
./state/frontend/etc/voms-gridmap.txt
[dbs3-test2 srv 1003] find . -name *.json
./HG2108e/config/frontend/x509_scitokens_issuer/dn_mapping.json
./HG2108e/config/frontend/x509_scitokens_issuer/rules.json
./HG2108e/config/frontend/x509_scitokens_issuer/x509_scitokens_issuer_app.json
./HG2108e/sw.yuyi/slc7_amd64_gcc630/external/x509-scitokens-issuer/v0.6.2-comp5/configs/dn_mapping.json
./HG2108e/sw.yuyi/slc7_amd64_gcc630/external/x509-scitokens-issuer/v0.6.2-comp5/configs/rules.json
./state/frontend/x509_scitokens_issuer/dn_mapping.json
./state/frontend/x509_scitokens_issuer/rules.json
./state/frontend/x509_scitokens_issuer/x509_scitokens_issuer_app.json

```
Thanks,
Yuyi

**Comment by Panos512** [comment]
Hi Yuyi,

Does the cron run? 
I’m not sure bout your installation but in FEs a cron runs that generates the file.
The cron is:
```
*/4 * * * * . /data/srv/current/apps/frontend/etc/profile.d/init.sh && PYTHONPATH=/data/srv/current/auth/frontend:$PYTHONPATH /data/srv/current/config/frontend/mkauthmap  -c /data/srv/current/config/frontend/mkauth.conf -o /data/srv/state/frontend/etc/authmap.json 
```

You can try running manually:
```
/data/srv/current/config/frontend/mkauthmap  -c /data/srv/current/config/frontend/mkauth.conf -o /data/srv/state/frontend/etc/authmap.json
```
if the cron is not there

Cheers,
Panos

**Comment by yuyiguo** [comment]
Hi Panos,

I did have the cron running, but it had errors. Please see the manually running the command.
Is the new FE py2 compatible?
Thanks,
Yuyi


```

[dbs3-test2 tmp 1018] sudo /data/srv/current/config/frontend/mkauthmap  -c /data/srv/current/config/frontend/mkauth.conf -o /data/srv/state/frontend/etc/authmap.json
Enter PEM pass phrase:
Traceback (most recent call last):
  File "/data/srv/current/config/frontend/mkauthmap", line 204, in <module>
    roles = request(uri)
  File "/data/srv/current/config/frontend/mkauthmap", line 70, in request
    result = requests.get(url, cert=cert, verify='/etc/ssl/certs/CERN-bundle.pem')
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 762, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 254, in ssl_wrap_socket
    context.load_cert_chain(certfile, keyfile)
IOError: [Errno 22] Invalid argument
```

**Comment by Panos512** [comment]
OK this is strange.
There are two things that we should first check in order to debug that: 
1. The DN of the certificate should be this one: https://cms-cric.cern.ch/accounts/account/list/?dn=Yuyi+Guo&is_active=1 . If not we should add the DN to CRIC.
2. The `/etc/robots/robotcert.pem` and `/etc/robots/robotkey.pem` files are correctly set. These should be the usual pem and key files generated from pk12, at least this is the process with CERN certificates. I'm asking that cause I see it asks for the PEM pass phrase, I think this should not happen if you pass the key file (I might be wrong on this one).

**Comment by yuyiguo** [comment]
Hi Panos,
```
[dbs3-test2 ~ 1003] ls -l /afs/cern.ch/user/y/yuyi/.globus/*.pem
-rw-r--r--. 1 yuyi zh 3295 Nov 13  2020 /afs/cern.ch/user/y/yuyi/.globus/usercert.pem
-rw-------. 1 yuyi zh 1958 Nov 13  2020 /afs/cern.ch/user/y/yuyi/.globus/userkey.pem
```
In the VM, the /`etc/robots/robotcert.pem` and `/etc/robots/robotkey.pem` files  are the same as what in `/afs/cern.ch/user/y/yuyi/.globus/`.

```
[dbs3-test2 ~ 1003] voms-proxy-init --voms cms -rfc
Enter GRID pass phrase:
Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo
Creating temporary proxy ...................... Done
Contacting  voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "cms" Done
Creating proxy ........................................................... Done
```
```
[dbs3-test2 ~ 1004] voms-proxy-info
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo/CN=744436698
issuer    : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo
identity  : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo
type      : RFC compliant proxy
strength  : 1024 bits
path      : /tmp/x509up_u5252
timeleft  : 11:58:23
```
The DN of the certificate is the same as in `https://cms-cric.cern.ch/accounts/account/list/?dn=Yuyi+Guo&is_active=1 `

**Comment by vkuznet** [comment]
@yuyiguo , the certs used by a cron, and therefore they should not have any passphrase. If you want to use your certs for testing make your key pem file to be passphrase free, e.g.
```
Remove passphrase
1. save userkey.pem
2. openssl rsa -in userkey.pem -out userkey_nopass.pem
3. chmod 0400 userkey_nopass.pem
```
Then, you can use `userkey_nopass.pem` in a cron.

**Comment by yuyiguo** [comment]
@vkuznet 

Thanks you very much. Removing the passphrase worked for 
`sudo /data/srv/current/config/frontend/mkauthmap  -c /data/srv/current/config/frontend/mkauth.conf -o /data/srv/state/frontend/etc/authmap.json`

The cron works too.

**Pull request merged**
