### PR TITLE
fix rucio instance for workqueue

### PR DESCRIPTION
**Pull request by todor-ivanov**

### CODE REVIEW

**Comment by amaltaro** [comment]
+1

**Comment by amaltaro** [comment]
@muhammadimranfarooqi please feel free to merge this PR.

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

Do we also need this change in `services_config` repository?

**Comment by amaltaro** [comment]
It's not needed. services_config should have the correct values in the correct branch (just doubled-checked and it's correct!). Thanks for checking though!

**Pull request merged**
