### PR TITLE
PPS layouts with pixel error plots

### PR DESCRIPTION
**Pull request by fabferro**
This PR introduces new layouts for PPS pixel error plots that have been implemented in CMSSW_13_0_0 by PR#40668.

The new layouts have been tested deploying private offline and dev GUIs.

### CODE REVIEW

**Comment by arooshap** [comment]
Hi @fabferro, I have incorporated the changes in the testbed VMs `vocms0132` and `vocms0731` with the latest release `HG2303b`. Please validate the changes. :)

**Comment by arooshap** [comment]
Hi @fabferro, may I have your username to ensure that you have access to the testbed VMs? 

For the second question, I think you can send an email to the conveners of the DQM team at `cms-PPD-conveners-DQM-DC@cern.ch`. I am also tagging some relevant people here, in case they can help with this: @lwang046, @rovere, @micsucmed, @andrius-k.

**Comment by fabferro** [comment]
> Hi @fabferro, may I have your username to ensure that you have access to the testbed VMs?
> 
> For the second question, I think you can send an email to the conveners of the DQM team at `cms-PPD-conveners-DQM-DC@cern.ch`. I am also tagging some relevant people here, in case they can help with this: @lwang046, @rovere, @micsucmed, @andrius-k.

Thanks @arooshap. My username is ferro

**Comment by arooshap** [comment]
Hi @fabferro, it looks like you did not have the permission to access the testbed VMs. I have updated the permissions, and you should be able to login to the testbed VMs.

Let me know if you require any further assistance. Thank you!

**Pull request merged**
