### PR TITLE
Adding outages of cmsweb for alertmanager in InstallProd

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by vkuznet** [comment]
+1

**Comment by vkuznet** [comment]
Muhammad, I suggest that you also add annotation using new monit tool. It should be available in /cvmfs/cms.cern.ch/cmsmon/monit, but there is a delay in CMSSW builds, so the newest version of this tool is in /cvmfs/cms-ib.cern.ch/latest/cmsmon/monit.

So, you should use it as following:
```
   # provide annotation to MONIT via a.json file
   monit -token admin.token -annotation=a.json
   # or use input options
   monit -token admin.token -annotation="some message" -tags=cmsweb -trange=now-10m
```
You should probably use Unix timestamp format to give more precise time, e.g.
```
monit -token admin.token -annotation="some message" -tags=cmsweb -trange=1592914422-2h
```

To run it you'll need admin token though.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

How to get admin token?

**Comment by vkuznet** [comment]
We will issue one, but I need to discuss with CERN MONIT team how to reduce its rights first, may be we can get a dedicated token for annotations.

**Comment by vkuznet** [comment]
[ProtonMail]

Secure email based in Switzerland

You have received a secure message from

vkuznet@protonmail.com

I'm using ProtonMail to send and receive secure emails. Click the link below to decrypt and view my message.

[[ProtonMail]View Secure Message](https://mail.protonmail.com/eo/s7gKHcs3_dVhpx_zkttowJG56EzStHZXYofeOuw0rsj9sE08VF4t-uwM8Nj5alZGlFWE_hLwmU3pNHPUVWHasg==)
[?What is this?](https://protonmail.com/support/knowledge-base/secure-messages/)

Password Hint:

None

Expiration:

2020-06-27 17:55:24 GMT (24 hours after this message was sent)

This message was secured by ProtonMail. ProtonMail uses end-to-end encryption to secure private communications. To send your own secure messages, visit https://protonmail.com

**Comment by vkuznet** [comment]
Muhammad, did you get the token I sent you separately? Can we close this ticket now?

**Pull request merged**
