### PR TITLE
Added three prefiring ratio plots for L1T Objects (Muon, EGamma, Jets) to L1T shifter workspace

### PR DESCRIPTION
**Pull request by jaisatul**
The following plot paths have been added to the end of shift_l1t_layout.py  (L1T shifter workspace). These plots are needed in shifter workspace for online pre-firing monitoring.

L1T/L1TObjects/L1TMuon/timing/First_bunch/Ratio_L1TMuons_BX_FirstBunch_minus1,
L1T/L1TObjects/L1TJet/timing/First_bunch/Ratio_L1TJet_BX_FirstBunch_minus1,
L1T/L1TObjects/L1TEGamma/timing/First_bunch/Ratio_L1TEGamma_ptmin_20p0_gev_BX_FirstBunch_minus1

### CODE REVIEW

**Comment by nothingface0** [comment]
Hey @jaisatul, the patch is applied on our [playback machines](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Shift;size=M;root=00%20Shift/L1T;focus=;zoom=no;). I can see the plots, but they're empty. Is this expected?

**Comment by jaisatul** [comment]
Hi @nothingface0,
Any update on this PR?

**Comment by nothingface0** [comment]
Hey @jaisatul really sorry, notifications keep getting drowned in a sea of emails. 

Our playback (same link as above should work) is currently running with run 382343. Is it any better?

**Comment by jaisatul** [comment]
Hi @nothingface0,
I checked the playback. The plots are sometimes empty and sometimes not depending on the prefiring situation. It looks fine to me.

**Comment by nothingface0** [comment]
This PR has now been deployed in production (online)!

**Comment by jaisatul** [comment]
@nothingface0 
Great! Thanks for the notification!

**Pull request merged**
