### PR TITLE
Changes to DT DQM layouts, workspaces-online.py and DT Render Plugin …

### PR DESCRIPTION
**Pull request by jfernan2**
…affecting online DT DQM.
Summary of changes:

-Layouts additions: added Out plots in addition to the default In plots in TriggerSynch, TriggerBasics and TriggerPosLUTs
-Change colours in DataIntegritySummary plot and definition to reflect only ROB errors
-Changes in workspaces-online.py to cope with the modifications

### CODE REVIEW

**Comment by threus** [comment]
@BrunoCoimbra could you please merge this PR?
Thanks, Tomas for DQM

**Comment by threus** [comment]
@jfernan2 you heavily modified workspaces-online.py, please update the branch with only the modifications relevant to DT. Thanks

**Comment by jfernan2** [comment]
Hi Tomas, 
now it is fine. I had mixed workspaces-online with the version loaded in my local GUI, HG1730i, as recommended in https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMGuiForUsers#How
Apologies for the incovenience.
Thanks

**Comment by threus** [comment]
@BrunoCoimbra could you please merge this PR?
Thanks, Tomas for DQM

**Pull request merged**
