### PR TITLE
Add ECAL DCC desync DQM trend plots and update description for Integrity summary plot for online & offline ECAL DQM

### PR DESCRIPTION
**Pull request by kyungminparkdrums**
This PR **[1]** adds new plots to to the Layouts in the ECAL workspace **and** **[2]** updates the description of Integrity Summary plot in online and offline DQM.

PRs in the CMSSW are made here: [CMSSW 14_0_13](https://github.com/cms-sw/cmssw/pull/45761) [CMSSW Master PR](https://github.com/cms-sw/cmssw/pull/45766)

### CODE REVIEW

**Comment by nothingface0** [comment]
Thank you @kyungminparkdrums !

This is now deployed on [playback](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Ecal;size=M;root=Ecal/Layouts;focus=;zoom=no;).

@rseidita will also deploy https://github.com/cms-sw/cmssw/pull/45761 soon.

**Comment by nothingface0** [comment]
@kyungminparkdrums the PR is also applied to the [offline-test](https://cmsweb.cern.ch/dqm/offline-test/) machine. Let us know how it looks.

**Comment by kyungminparkdrums** [comment]
@nothingface0 They look good, thank you very much!

**Comment by nothingface0** [comment]
@kyungminparkdrums this is now deployed on the offline DQMGUI

**Pull request merged**
