### PR TITLE
couch 1.6 update

### PR DESCRIPTION
**Pull request by ticoann**
Need for couch 1.6 update

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, please review

**Comment by vkuznet** [comment]
Please add ssl_certificate_max_depth = 3 at the end of replicator section. This is required to handle enclosed certificates, like CERN proxies.

**Comment by ticoann** [comment]
Thanks Valentin, I missed that. I updated the patch. Also it seem following are useful parameters to set as well. Should we set them?
use_checkpoints = true
checkpoint_interval = 5000
Here is the reference
https://people.apache.org/~dch/snapshots/couchdb/20140715/new-docs-build/html/config/replicator.html

**Comment by vkuznet** [comment]
Seangchan,
yes they're good to include, but I'll make a comment above them saying that
they're introduced with CDB1.6
Valentin.

**Comment by geneguvo** [comment]
Hi guys,
I'll not include this PR while we haven't concluded the replication tests with CDB16. I know, for instance, you'd need:
use_checkpoints = false
max_replication_retry_count = infinity

We may want to fine tune it too, including things like:
socket_options = [{keepalive, true}, {nodelay, true}]
and increasing size of send/recv buffers, etc..

Besides, "use_checkpoints" was introduced in CDB16. So we should not pick it before the wmagents are ready to move.

Finally, although "ssl_certificate_max_depth = 3" would work for the current cmsweb chain of certificates, this might eventually change. Default reasonable value for max depth is usually 10.

Cheers,
Diego.

**Comment by ticoann** [comment]
Thanks Diego, I updated the patch as you suggested. We will run the test first, so please don't merge yet.

**Comment by amaltaro** [comment]
Diego, we have been running all ours tests with this patch and it's good to be merged now.

**Pull request closed without merging**
