### PR TITLE
PPS layout improvements and updates

### PR DESCRIPTION
**Pull request by fabferro**
This PR improves and updates PPS layouts:
- two new diamond stations are linked in the layouts
- log scale is introduced in a plot to improve readability
- error code plots are now correctly linked
- shift workspace has been improved to ease shifter work (also added plots in the common space)

The PR have been tested with the deployment of an Offline Local GUI and it behaves as expected.

These changes should be deployed to the Online GUI too asap.

### CODE REVIEW

**Comment by arooshap** [comment]
Hi @fabferro,

Your PR has been incorporated in the testbed release tagged `HG2305c`, in the vocms0132 and vocms0731 testbed VMs. Kindly validate it, so that we can incorporate it in the production release later this week or at the start of the next week.

Thanks!

**Comment by fabferro** [comment]
@arooshap If I deploy and start my own instance of HG2305c I can see my changes.
Though, if I open https://cmsweb.cern.ch/dqm/offline-test I can't see any (it's running on vocms731)... Is this link the wrong one?

**Comment by arooshap** [comment]
@fabferro, I confirm that the vocms0731 is actually running the latest release: 
```
[apervaiz@vocms0731 srv]$ ls -lrt
total 96
drwxrwxr-x. 31 cmsweb zh      4096 Sep  4  2020 logs
drwxrwxr-x.  2 cmsweb zh      4096 Sep  4  2020 enabled
drwxr-xr-x.  3 cmsweb zh      4096 Jan 21  2021 newDQMGUI
-rwxr-xr-x.  1 root   root    4328 Jan 28  2021 sudoers
-rwxr-xr-x.  1 cmsweb zh       390 Feb 15  2021 kinit.sh
drwxrwxr-x.  6 cmsweb _sw     4096 Sep 30  2021 be
drwxrwxr-x. 31 cmsweb zh      4096 Jun 29  2022 state
drwxrwxr-x.  5 cmsweb _sw     4096 Jun 29  2022 log-bosstraping-beHG1806j
drwxr-x---. 26 cmsweb _config 4096 Jul  1  2022 auth
drwxrwxr-x.  6 cmsweb _sw     4096 Oct 21  2022 beHG2211a
drwxrwxr-x.  6 cmsweb _sw     4096 Oct 21  2022 beHG2211b
drwxrwxr-x.  6 cmsweb _sw     4096 Oct 25  2022 beHG2211c
drwxrwxr-x.  6 cmsweb _sw     4096 Oct 31  2022 beHG2211d
drwxrwxr-x.  6 cmsweb _sw     4096 Nov  2  2022 beHG2211e
drwxrwxr-x.  6 cmsweb _sw     4096 Nov  3  2022 beHG2211f
drwxrwxr-x.  6 cmsweb _sw     4096 Nov  3  2022 beHG2211f-v2
drwxrwxr-x.  6 cmsweb _sw     4096 Nov 18  2022 beHG2212a
drwxrwxr-x.  6 cmsweb _sw     4096 Nov 29  2022 beHG2212b
drwxrwxr-x.  6 cmsweb _sw     4096 Dec  2  2022 beHG2212c
drwxrwxr-x.  6 cmsweb _sw     4096 Dec  7 13:35 beHG2212d
drwxrwxr-x.  6 cmsweb _sw     4096 May  2 10:59 beHG2304a
drwxrwxr-x.  6 cmsweb _sw     4096 May 22 14:25 beHG2305a
drwxrwxr-x.  6 cmsweb _sw     4096 Jun  5 16:58 beHG2305c
lrwxrwxrwx.  1 cmsweb zh         9 Jun  5 16:58 current -> beHG2305c
[apervaiz@vocms0731 srv]$
```

I am not sure about the URL though because I don't have a vivid idea about how DQMGUI works.

**Comment by fabferro** [comment]
> @fabferro, I confirm that the vocms0731 is actually running the latest release:
> 
> ```
> [apervaiz@vocms0731 srv]$ ls -lrt
> total 96
> drwxrwxr-x. 31 cmsweb zh      4096 Sep  4  2020 logs
> drwxrwxr-x.  2 cmsweb zh      4096 Sep  4  2020 enabled
> ...
> lrwxrwxrwx.  1 cmsweb zh         9 Jun  5 16:58 current -> beHG2305c
> [apervaiz@vocms0731 srv]$
> ```
> 
> I am not sure about the URL though because I don't have a vivid idea about how DQMGUI works.

Mmm... so?
I can say that HG2305c is validated because I've seen it working correctly in my private replay.
While, if you want me to check that running on vocms0731, you should tell me how I can connect to it and see it.

**Comment by fabferro** [comment]
@arooshap can we consider this validated?
What about the implementation in the Online GUI?

**Comment by arooshap** [comment]
@fabferro yes, as you made sure that the HG2305c release incorporates the changes as you mentioned.

For the implementation, we have the coming Monday for the deployment in production(tentative, as of yet).

**Comment by fabferro** [comment]
Hi @arooshap. I can't see these changes in the Online GUI yet. Do you know when they will become available for the shifters in P5? Thanks.

**Comment by arooshap** [comment]
@fabferro I incorporated your PR already in the last production release that we had on Tuesday(last week). I am not sure why the changes are not appearing/reflecting. 

Can you please have a look or contact the DQM team?

**Pull request merged**
