### PR TITLE
shift_l1t_layout is updated

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo
Tests OK.
Can you merge this?
Thanks

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo: Please postpone the merging.
@EsmaeelEskandari Please, never never never change a PR that has already been tested, deployed on production and requested to be merged. A new PR would have been the right thing to do.
Since it's already done now. Please follow the rest of the normal procedure: I.e. I expect a mail when you want to start testing this.

**Comment by EsmaeelEskandari** [comment]
Dear Broen,

Sorry for the inconvenience.
I didn't know this point.
For the future I will make a fresh PR for non-merging ones.
Should I do something now about this new PR?

Cheers,
Esmaeel.

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo
Tests OK.
Can you merge this?
Thanks

**Pull request closed without merging**
