### PR TITLE
New (cumulative) plots

### PR DESCRIPTION
**Pull request by dinardo**
I've implemented new plots in the application that keep the data all along the run (cumulative).
- Mauro.

### CODE REVIEW

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo
Tests OK.
Can you merge this?
Thanks

**Comment by dinardo** [comment]
Just a curiosity,
why it has been closed and NOT merged ?
Many thanks,
- Mauro.

**Comment by vanbesien** [comment]
I don't really understand your question @dinardo, your commit is right there merged in the master branche: https://github.com/dmwm/deployment/commits/master

Cheers,

Broen

**Comment by dinardo** [comment]
Hi Broen,
there are different modes to close a PR, either "Closed" or "Merged".
I was expecting "Merged". But if you say that my PR has been merged,
then it's fine with me.
Cheers,
- Mauro.

**Comment by geneguvo** [comment]
Hi Dinardo,
We don't really "merge" the branches, but we pick the commits, modify if needed (clean, squash commits, fix if any, etc) and finally push, closing the corresponding PR. We also keep  the original author and author-date.
Cheers,
Diego.

**Pull request closed without merging**
