### PR TITLE
Change the scale of hitefficiency map

### PR DESCRIPTION
**Pull request by MRD2F**
Change of the scale for the "HitEfficiency_per_SignedModule_per_SignedLadder_PXLayer_1"  map, from 0.95 to 0.80

### CODE REVIEW

**Comment by fioriNTU** [comment]
@MRD2F this is not correct, the layer 1 efficiency will have the same limit at 0.95 like this, please update the PR to have two exclusive cases ... the second if will set back the scale to 0.95

**Comment by fioriNTU** [comment]
@MRD2F thanks a lot, I donno what happened with the indentations and spaces, but it looks ok!

**Comment by MRD2F** [comment]
Oh, sorry I saw it know, me neither, from my text editor it looked fine. Thanks to you!

Regards, 
Maria Di Domenico

**Comment by threus** [comment]
@h4d4 , Tests are OK. Could you please merge this?
Thanks,
Tomas for DQM

**Pull request merged**
