### PR TITLE
fix pixel heterogeneous online DQM layout

### PR DESCRIPTION
**Pull request by mmusich**
title says it all, I notice browsing the online GUI some plot were empty:

Screenshot from 2024-10-02 16-58-54

@nothingface0 FYI

### CODE REVIEW

**Comment by nothingface0** [comment]
Thanks @mmusich, [looks good](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=SiPixelHeterogeneous;size=M;root=Quick%20collection;focus=;zoom=no;). 

I will check later with another run with GPU comparison data as well.

**Comment by mmusich** [comment]
@nothingface0 as it looks good, can you deploy it in the online GUI?

**Comment by nothingface0** [comment]
@mmusich It's now deployed [online](https://cmsweb.cern.ch/dqm/online/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=SiPixelHeterogeneous;size=M;root=Quick%20collection;focus=;zoom=no;).

**Comment by mmusich** [comment]
> It's now deployed [online](https://cmsweb.cern.ch/dqm/online/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=SiPixelHeterogeneous;size=M;root=Quick%20collection;focus=;zoom=no;).

Thanks!

**Comment by mmusich** [comment]
is there anything missing for this PR to be merged?

**Pull request merged**
