### PR TITLE
Adding EOS paths for logs to archive

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
We have not space for EOS which will be used as logs archival. The project space is reserved at `/eos/project/c/cmsweb-http/`. @amaltaro @vkuznet could you please review. Thanks

**Comment by muhammadimranfarooqi** [comment]
I have tested this on testbed frontend and logs were copied properly.

```
[mimran@lxplus725]/eos/project/c/cmsweb-http/logs% ls vocms0135
access_log_201804.zip  access_log_201901.zip  access_log_201910.zip  error_log_201804.zip  error_log_201901.zip  error_log_201910.zip  expired-tmp
access_log_201805.zip  access_log_201902.zip  access_log_201911.zip  error_log_201805.zip  error_log_201902.zip  error_log_201911.zip  start_stop.log
access_log_201806.zip  access_log_201903.zip  access_log_201912.zip  error_log_201806.zip  error_log_201903.zip  error_log_201912.zip  zir0BXMO
access_log_201807.zip  access_log_201904.zip  access_log_202001.zip  error_log_201807.zip  error_log_201904.zip  error_log_202001.zip
access_log_201808.zip  access_log_201905.zip  access_log_202002.zip  error_log_201808.zip  error_log_201905.zip  error_log_202002.zip
access_log_201809.zip  access_log_201906.zip  access_log_202005.zip  error_log_201809.zip  error_log_201906.zip  error_log_202005.zip
access_log_201810.zip  access_log_201907.zip  access_log_202010.zip  error_log_201810.zip  error_log_201907.zip  error_log_202010.zip
access_log_201811.zip  access_log_201908.zip  access_log_202011.zip  error_log_201811.zip  error_log_201908.zip  error_log_202011.zip
access_log_201812.zip  access_log_201909.zip  access_log_202012.zip  error_log_201812.zip  error_log_201909.zip  error_log_202012.zip
```

**Comment by amaltaro** [comment]
Perfect! I assume there is an access control list to avoid having unwanted folks reading our frontend logs, right?

**Comment by muhammadimranfarooqi** [comment]
Yes, I only provided access to `cms-service-webtools`  and dqm group

**Comment by amaltaro** [comment]
fine work!

**Pull request merged**
