### PR TITLE
updating pixel online layouts and renderplugins for much easier shifter monitoring

### PR DESCRIPTION
**Pull request by danduggan**
This fixes the LS-by-LS auto zoom issue, as well as a general restructuring of the shifter plots for online review.

### CODE REVIEW

**Comment by danduggan** [comment]
@vanbesien sorry, there was a small bug so i had to update this, then to clean things up i squashed my commits to make it better for book-keeping. can you update the playback pretty please?

**Comment by vanbesien** [comment]
@danduggan Done on both test and playback.

**Comment by danduggan** [comment]
@vanbesien you are great, thanks. +1 for pushing the update to production.

**Comment by vanbesien** [comment]
@danduggan Dear Dan, It went into production yesterday evening. Kind regards.

@BrunoCoimbra , @geneguvo
Tests OK.
Can you merge this?
Thanks

**Comment by danduggan** [comment]
@vanbesien awesome, thanks!

**Pull request closed without merging**
