### PR TITLE
Disable T0 Reqmon CherryPy thread tasks from testbed VMs

### LINKED ISSUE #974: Disable t0reqmon cherrypy threads
Disable CherryPy threads from t0reqmon deployment.
Reason: These will be running from the k8s deployment instead (and we can't run 2 at the same time).

https://github.com/dmwm/deployment/blob/master/t0_reqmon/config.py#L74

### PR DESCRIPTION
**Pull request by khurtado**
Fixes #974

### CODE REVIEW

**Comment by amaltaro** [comment]
Together with this change, we need to start deploying `t0_reqmon` into k8s-testbed:
https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/t0_reqmon.yaml

**Comment by muhammadimranfarooqi** [comment]
@amaltaro @khurtado 

We need to update frontend rules for this? 

https://github.com/dmwm/deployment/blob/master/frontend/backends-k8s-preprod.txt

**Comment by muhammadimranfarooqi** [comment]
@khurtado 

The `vocms0127` does not exist anymore. You can safely remove this as well.

**Comment by amaltaro** [comment]
About frontend rules, it seems to be covered by your PR:
https://github.com/dmwm/deployment/pull/977

And about vocms0127, I suggest we create another PR this week and remove it from every single configuration.

**Comment by amaltaro** [comment]
LGTM!

**Pull request merged**
