### PR TITLE
CTPPS DQM update with pixel gui

### PR DESCRIPTION
**Pull request by popovvp**
update 2 files wth pixel plots:
workspaces-online.py,
ctpps-layouts.py

### CODE REVIEW

**Comment by threus** [comment]
@h4d4 , Tests are OK. Could you please merge this?
Thanks,
Tomas for DQM

**Comment by h4d4** [comment]
@threus, I've solved some conflict in this PR bon this files:
dqmgui/layouts/ctpps-layouts.py
dqmgui/workspaces-online.py

I guess that was because I first Squash and merge the last PR that change this same files, It's the PR: 
CTPPS: Diamond detectors layout #480 
https://github.com/dmwm/deployment/pull/480/files

Please, do me a favor and check that the code is as you need.
Thanks.

**Comment by threus** [comment]
Hi Lina, thanks for letting me know - I notice few things are missing (i.e. pixels in the workspaces-online.py, etc). @popovvp could you please check? 
If there was a conflict, maybe the best would be to unmerge this PR and let the developer rebase from the master branch (now that #480 is merged).

**Comment by popovvp** [comment]
Merging (on 23.05.17) branch 'master' into ctpps_pixel_gui is wrong. It simply substitute working ctpps pixel dqm  gui by diamonds, instead of updating with diamonds

**Comment by popovvp** [comment]
Revert "update with pixel gui (#478)"  removed completely original PR 478.
Please, somebody, take care to reestablish original PR478

**Pull request merged**
