### PR TITLE
Hcal relval Render Plugin development

### PR DESCRIPTION
**Pull request by spandeyehep**
I have created and modified following scripts in order to change HCAL workspace in relval server.

Added following render-plugin scripts:
1) dqmgui/style/HcalrelvalRenderPlugin.cc
2) dqmgui/style/HcalrelvalObjectCustomizer.h
3) dqmgui/style/HcalrelvalMaps.h

Added following layout scripts:
1) dqmgui/layouts/hcal_relval-layouts.py
2) dqmgui/layouts/hcalMC_relval-layouts.py

Modified following scipts:
1) dqmgui/workspaces-relval.py
2) dqmgui/server-conf-relval.py

I have summarized all the major changes here : https://spandey.web.cern.ch/spandey/files/slides/PR_oct_7.pdf

### CODE REVIEW

**Comment by hatakeyamak** [comment]
DQM experts. Did you have a chance to take a look? Can this be merged sometime soon?

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo
Tests OK.
Can you merge this?
Thanks

**Comment by vanbesien** [comment]
@spandeyehep standby to test this on the relval-test server as soon as the cmsweb people deploy a new test version

**Comment by hatakeyamak** [comment]
Thank you. Will you notify us here when the cmsweb people deploy a new test version?

**Comment by vanbesien** [comment]
@hatakeyamak @spandeyehep Of course I will notify you... and that moment is now... it was deployed an hour ago.
You can go and check on https://cmsweb.cern.ch/dqm/relval-test/
This is the test instance of the relval GUI. It contains an older subset of the data that you find on the production relval GUI, which should be more than sufficient for testing. In case of problems you can contact the DQM core team directly.

**Comment by spandeyehep** [comment]
@vanbesien @hatakeyamak  I am sorry I forgot to mention one important point. In HcalrelvalObjectCutomizer.h file, I used an algorithm which takes advantage of weblogs in order to extract last loaded sample(and eventually loads ranges etc. accordingly). The path of relval weblog directory has to be specified there. In my working code, I used the path of my local server weblog directory's location. 
Could you please make sure that the correct path is specified there?
Here is the line (#483) that needs to be changed: https://github.com/dmwm/deployment/blob/master/dqmgui/style/HcalrelvalObjectCustomizer.h#L483

**Comment by vanbesien** [comment]
@BrunoCoimbra , @geneguvo
Please un-merge.

We're placing this on hold.

**Comment by hatakeyamak** [comment]
@spandeyehep do you know how that line needs to be changed? If so, just change that line, and make another PR quickly?

**Comment by spandeyehep** [comment]
@hatakeyamak I don't know the path of log directory at the central server. If someone can provide me the path then I can make the change right away.

**Comment by vanbesien** [comment]
Hi guys,

In your summary slides this was presented as an update to the render plugins and change to some layouts.
Now that we saw that you're reading the log files of the webserver from withing the rendering process, I'm placing this in on hold and scheduling a more thorough review of the code by the experts in the DQM team.
I can already tell you that there is 0 chance that we will allow the path of any server specific folder to be hardcoded anywhere.
I can also tell you that we will never allow any plug-in to go read into the logs of the running application.
Next time you do this kind of development, please discuss with us first.

**Comment by hatakeyamak** [comment]
We understand and thank you for your message. Let's discuss offline how to go about it.

**Pull request merged**
