### PR TITLE
deployment script for wmstats server

### PR DESCRIPTION
**Pull request by ticoann**
@geneguvo, Diego, could you review the code?

This change include REST server (cherrypy) for wmstats which includes server side data cache and moved logDB thread from reqmgr2.
This is still initial version so there will be additional features to be added.
DataCache addition will use additional ~30MB of server side memory.

/wmstatsserver/data is the server uri for data service but will move to /wmstats/data when we relocate the wmstats source code from couchapp to html directly in WMCore/src. (we need to do some refactoring so it won't be this deployment)

Thanks

### CODE REVIEW

**Comment by geneguvo** [comment]
I need to review it carefully. Since other folks are waiting for a testbed yet this week, I'll leave to include these changes somewhere next week, on the next testbed opportunity, ok?

**Comment by ticoann** [comment]
That will be fine. Thanks.

**Comment by amaltaro** [comment]
@geneguvo Diego, as we discussed yesterday, we are planning to submit a WMCore request this evening and the new tags will require these deployment changes.
If you can review and deploy a new testbed this week, that would be awesome ;)

**Comment by geneguvo** [comment]
Hi,
I've reviewed it but did not test anything yet. Is this something I can test with current WM* versions or I definitely need to wait for Alan's PR this evening?

From the review, there are only minor changes to be done, which I'll do myself:
+ use /reqmon instead of /wmstatserver;
+ port 8299 is assigned to gitweb, I'll give it one of the ports from ReqMgr's port range 8240-8249;
+ need to remove the other bigcouch bits from the reqmon/deploy script if we'll drop it

Cheers,
Diego.

**Comment by amaltaro** [comment]
Diego, AFAIK it can be tested with the current head (tag 1.0.9.pre3), but I don't have these RPMs in my private repo. Better wait for Seangchan's confirmation, since he did all the job :)

**Comment by geneguvo** [comment]
I don't have them neither. Current RPMs point to 1.0.8.pre7, so I'll wait for either you or Seangchan to make a PR for cmsdist with the right versions to pick together with this major deployment changes.

**Comment by ticoann** [comment]
> Collaborator
> geneguvo commented 4 hours ago
> 
> Hi,
> I've reviewed it but did not test anything yet. Is this something I can test with current WM* versions or I definitely need to wait for Alan's PR this evening?

Yes this one won't work earlier than 1.0.9.pre3. I will create the new tag with Alan's patch and make the pull request.


> 
> From the review, there are only minor changes to be done, which I'll do myself:
> 
>     use /reqmon instead of /wmstatserver;

This one will eventually be wmstats (hopefully October deployment) when we move client code out of the couch app. If you still prefer to change reqmon I need to change in one place in  WMCore. Just let me know.

>     port 8299 is assigned to gitweb, I'll give it one of the ports from ReqMgr's port range 8240-8249;
>     need to remove the other bigcouch bits from the reqmon/deploy script if we'll drop it

Ah, I forgot to ask which port I should use. Yes please reassigned the new port.

Thanks Diego

> Cheers,
> Diego.

**Comment by geneguvo** [comment]
Let's keep /wmstatserver then.

**Pull request closed without merging**
