### PR TITLE
update for GE21-M-L1 recHit xy occupancy plot at onlineDQM shift workspace

### PR DESCRIPTION
**Pull request by Dongwoon77**
PR description:

In this PR, update for added GE21-M-L1 rechit xy occupancy plot at GEM onlineDQM GUI shift workspace.

- GE21-M-L1 rechit xy occupancy at GEM onlineDQM GUI

@jshlee @watson-ij @quark2

### CODE REVIEW

**Comment by nothingface0** [comment]
Hellow @Dongwoon77 , sorry for the late reply. 

This is deployed on our [playback machine](https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Shift;size=M;root=00%20Shift/GEM/Common;focus=GEM/RecHits/occ_xy_GE21-P-L2;zoom=no;). How does it look?

**Comment by Dongwoon77** [comment]
Dear @nothingface0 

It is good for me, that is expected update.

Thank you.
Dongwoon.

**Comment by nothingface0** [comment]
@Dongwoon77 should we deploy it on production?

**Comment by Dongwoon77** [comment]
Dear @nothingface0 

Yes it need to deploy on onlineDQM GUI

Thank you.
Dongwoon.

**Comment by nothingface0** [comment]
@Dongwoon77 It's now deployed on production.

**Comment by Dongwoon77** [comment]
@nothingface0 

Thank you!
Dongwoon

**Pull request merged**
