### PR TITLE
Starting the DQM sound alarm manager in the online P5 DQM GUI

### PR DESCRIPTION
**Pull request by andrius-k**
Starting a recently added DQM sound alarm manager that allows to enable/disable alarms for certain plots. The manager was added here: https://github.com/rovere/dqmgui/pull/53

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@andrius-k 

Is this PR ready to be included in upcoming release?

**Comment by andrius-k** [comment]
Hi @muhammadimranfarooqi 
Yes it is, I just added a comment to a gitlab issue with all dmwm/deployment PRs to be included to the following release.
Regards,
Andrius

**Comment by muhammadimranfarooqi** [comment]
Hi,
@andrius-k 
Actually you are late. Deployment is already running and about to finish. I'll include this in next iteration.

**Comment by andrius-k** [comment]
Hi @muhammadimranfarooqi
I thought the deadline for submitting PRs was 17th of February but this is fine for us as long as we can get the HG tag including this change (as well as 
https://github.com/dmwm/deployment/pull/849) for local (online) deployment.

**Comment by muhammadimranfarooqi** [comment]
Hi @andrius-k 

Yes. Actually I had to run this today due to DBS. However, I'll run next deployment on 17th Monday and will include this PR. 

Cheers

**Comment by andrius-k** [comment]
Hi @muhammadimranfarooqi
That sounds very good, thanks!
Regards,
Andrius

**Pull request merged**
