### PR TITLE
Moving SMNotifyDb_Url to secrets file

### PR DESCRIPTION
**Pull request by vytjan**
@amaltaro by accident I closed the other PR. This has the same changes, but with only one commit.

### CODE REVIEW

**Comment by h4d4** [comment]
@vytjan @amaltaro guys therefore those changes are ready to be merged?

**Comment by amaltaro** [comment]
It looks good to me Vytas! (Next you can explicitly ask for my review via GH "Reviewers")

**Comment by vytjan** [comment]
Thanks Alan, next time I will ask for you review.
Could this PR be merged already?

**Comment by vytjan** [comment]
@h4d4 Lina could you please merge this?

**Comment by h4d4** [comment]
@vytjan merged.

**Pull request merged**
