### PR TITLE
Redefine color palette for CaloLayer2,BMTF,uGMT,uGT and add color palette for uGT in L1TEMU for online DQM 

### PR DESCRIPTION
**Pull request by pgianneios**

### CODE REVIEW

**Comment by threus** [comment]
@pgianneios please fix the conflicts

**Comment by pgianneios** [comment]
https://github.com/threus I fixed the conflicts

**Comment by thomreis** [comment]
@threus Paris has fixed the conflicts :-)

**Comment by threus** [comment]
@h4d4 , Tests are OK. Could you please merge this?
Thanks,
Tomas for DQM

**Pull request merged**
