### PR TITLE
Adapted RenderPlugin to cope with histogram ShitFillLast removed

### PR DESCRIPTION
**Pull request by dinardo**
A DQM shifter pointer me to a feature of the layout that might be misunderstood,
therefore I decided to simplify the histograms: I removed the ShiftFillLast and I
made all plots with a fixed X axis range that span over 20h of uninterrupted running
- Mauro.

### CODE REVIEW

**Comment by dinardo** [comment]
I was wondering why this is not yet merged.
Many thanks,
- Mauro.

**Comment by vanbesien** [comment]
This is not yet merged, because it is not yet tested on the online.
We follow normal procedure here.
As soon as your pull requests for cmssw on the online merge without problems, you will be able to test the modifications to the GUI. And as soon as you confirm that you successfully tested this PR on the GUI, we can continue.
Please check https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMGuiForUsers if you have questions.

**Comment by dinardo** [comment]
Hi Broen,
indeed, this pull request it tight to the CMSSW PR #11446.
Therefore they should be deployed together.
Many thanks,
- Mauro.

**Comment by dinardo** [comment]
Hi again,
I think the CMSSW-PR (#11446) related to this PR has been merged.
I don't understand why here it says: https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
"Waiting list for new PRs on top of HG1507g"
Is there something I have to do ?
Many thanks,
- Mauro.

**Comment by vanbesien** [comment]
Hi Mauro,
It's indeed in the waiting list, because I had to remove it again to test other PR's that had to go to production. (It speaks for itself that the test and production system should be 100% aligned.)
I have other patches in the pipeline as well, so there will be an update of the test system very soon.
I will let you know.

**Comment by vanbesien** [comment]
@BrunoCoimbra @geneguvo 
Tests succeeded. Please merge.
Thanks

**Pull request closed without merging**
