### PR TITLE
add HLTTrackingRenderPlugin

### PR DESCRIPTION
**Pull request by mtosi**
this PR is meant for handling plots under HLT/Tracking and HLT/SiStrip
this should be used in all the GUI flavours (online, offline and relval)

hope everything is fine
@deguio @vanbesien

### CODE REVIEW

**Comment by vanbesien** [comment]
Hi Mia,

When merging git complains about whitespace errors.
Indeed, I see trailing spaces on lines 144, 152, 160, 229, 234, 240, 374.
Can you fix this?
I'm installing on the test system.

**Comment by vanbesien** [comment]
Hi Mia,
The plugin doesn't build:
/data/srv/current/config/dqmgui/style/HLTTrackingRenderPlugin.cc:84:8: error: unused parameter 'c' [-Werror=unused-parameter]
   void preDrawTH2F( TCanvas *c, const VisDQMObject &o )

Can you check?

**Comment by vanbesien** [comment]
ping

**Comment by vanbesien** [comment]
Hey @mtosi , what shall we do with this.
You spent time on developing this, I guess it will still be useful to revive this.

Cheers,

Broen

**Comment by mtosi** [comment]
ciao
you are right, but I do not have the time now to fix this issue
unfortunately :(
  mia

On Fri, Aug 19, 2016 at 10:48 AM, Broen van Besien <notifications@github.com

**Comment by threus** [comment]
Hi @mtosi , has anything changed about your availability to finalise this PR?

**Comment by mtosi** [comment]
not in the short term :(
sorry
  mia

**Comment by amaltaro** [comment]
Given the lack of activity, I suggest we close this PR @h4d4

**Comment by h4d4** [comment]
@amaltaro Alan,

yes you, right a lot of time without none update here.
Closing.

Best Regards, Lina.

**Pull request closed without merging**
