### PR TITLE
Add ms-pileup redirect to port 8241

### PR DESCRIPTION
**Pull request by vkuznet**
This PR contains redirect rules for MSPileup service which now served on k8s at port 8241.

### CODE REVIEW

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I changed the port of MS pileup service to be 8241, I already changed CMSKubernetes, see https://github.com/dmwm/CMSKubernetes/commit/eca72978f74ea49f020a31eee866bd96f0ba7ef2 and corresponding configs in https://gitlab.cern.ch/cmsweb-k8s/services_config/-/commit/406a506401cd509531a0b8a28de6ff39a230b6b1 (both in test and preprod branches). Please merge and deploy these changes to testbed, and also update http dashboard to include new service and its port at https://cms-http-group.docs.cern.ch/cmsweb/dashboard/

@amaltaro this is for your information.

**Comment by arooshap** [comment]
@vkuznet @amaltaro the frontend in the testbed is updated now to reflect these changes. I have also deployed ms-pileup with the latest configuration changes in the CMSKubernetes and services_config repository.

**Comment by vkuznet** [comment]
@arooshap thank you, the service is working now:
```
scurl https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/status
{"result": [
 {
  "wmcore_version": "2.1.7",
  "microservice_version": "2.1.7",
  "microservice": "MSManager",
  "status": "OK",
  "thread_id": "MSPileup",
  "start_time": "Fri, 17 Feb 2023 13:42:12 UTC",
  "end_time": "Fri, 17 Feb 2023 13:42:12 UTC",
  "execution_time": 0.000161,
  "error": "",
  "total_num_pileups": 0,
  "total_num_rules": 0
}]}
```
and we can even query the data:
```
scurl https://cmsweb-testbed.cern.ch:8443/ms-pileup/data/pileup?campaigns=test
{"result": [
 {
  "pileupName": "/sdkjfhsdkf/klsjdflksdj/PREMIX",
  "pileupType": "classic",
  "insertTime": 1675707397,
  "lastUpdateTime": 1675707397,
  "expectedRSEs": [],
  "currentRSEs": [],
  "fullReplicas": 1,
  "campaigns": [
    "test"
  ],
  "containerFraction": 0.5,
  "replicationGrouping": "ALL",
  "activatedOn": 1675707397,
  "deactivatedOn": 1675707397,
  "active": true,
  "pileupSize": 0,
  "ruleList": []
}]}
```

**Comment by amaltaro** [comment]
Wonderful, thank you!

**Pull request merged**
