### PR TITLE
add dedicated MC TK Phase-2 workspace and RenderPlugin

### PR DESCRIPTION
**Pull request by mmusich**
Title says all. This is meant only for the RelVal GUI

cc: @sroychow @arossi83 @gabriel-rmrz @valeriadamante 

Validated in a private instance of the RelVal GUI.
   * the new "MC Tk Phase-2" workspace is displayed correctly:
   
image

   * 2D heatmaps are displayed correctly:
  
image

### CODE REVIEW

**Comment by mmusich** [comment]
@jfernan2 FYI

**Comment by jfernan2** [comment]
@muhammadimranfarooqi  this can be also included in the same shot as #1047 and #1049

**Comment by muhammadimranfarooqi** [comment]
@mmusich 

Could you please confirm this PR is ready for deployment as well in production environment. Thanks

**Comment by mmusich** [comment]
@muhammadimranfarooqi confirmed, thank you.

**Pull request merged**
