### PR TITLE
Fixing exporter issue in vocms0742

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

As discussed in the meeting and after applying this fix. The issues is still not resolved. 

[cmsweb@vocms0742 exporters]$ sudo bashs -l -c "/data/srv/current/config/exporters/manage status 'I did read documentation'"
node_exporter service is RUNNING, PID=16378
UID        PID  PPID  C STIME TTY          TIME CMD
root     16378     1  1 15:36 pts/0    00:00:00 node_exporter --web.listen-address=:19000
couchdb_exporter service is RUNNING, PID=16411
UID        PID  PPID  C STIME TTY          TIME CMD
root     16411     1  1 15:36 pts/0    00:00:00 couchdb_exporter -couchdb.uri=http://localhost:5984 -logtostderr=true -databases=reqmgr_workload_cache,reqmgr_config_cache,acdcserver,reqmgr_auxiliary -databases.views=false -telemetry.address=:15984
das2go_exporter service is RUNNING, PID=16389
UID        PID  PPID  C STIME TTY          TIME CMD
root     16389     1  1 15:36 pts/0    00:00:00 das2go_exporter -address :18217
mongodb_exporter service is RUNNING, PID=16400
UID        PID  PPID  C STIME TTY          TIME CMD
root     16400     1  0 15:36 pts/0    00:00:00 mongodb_exporter -mongodb.uri mongodb://localhost:8230 --web.listen-address :18230 -groups.enabled
reqmgr2ms_exporter service is NOT RUNNING

**Comment by vkuznet** [comment]
Muhammad,
this is more tricky. If you'll look into logs of one of reqmgr2ms_exporters, e.g.
/data/srv/logs//exporters/ms-transferor_exporter-20200507-vocms0742.log
you'll see this message
Starting: process_exporter -pid=5955 -prefix ms-transferor
panic: descriptor Desc{fqName: "ms-transferor_process_cpu_seconds_total", help: "Total user and system CPU time spent in seconds (process collector)", constLabels: {}, variableLabels: []} is invalid: "ms-transferor_process_cpu_seconds_total" is not a valid metric name

The issue is that you used '-' sign for exporter prefixes, see
/data/srv/current/config/exporters/manage
and the function which use these prefixes is:
reqmgr2ms_monitors()
{
    # start reqmgr2ms exporter
    wait4proc "reqmgr2ms" # check for pattern that it is running
    process_monitor.sh /data/srv/state/reqmgr2ms/ms-transferor.pid ms-transferor ":18247" 15 \
        </dev/null 2>&1 | rotatelogs $LOGDIR/ms-transferor_exporter-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
    process_monitor.sh /data/srv/state/reqmgr2ms/ms-monitor.pid ms-monitor ":18248" 15 \
        </dev/null 2>&1 | rotatelogs $LOGDIR/ms-monitor_exporter-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
    process_monitor.sh /data/srv/state/reqmgr2ms/ms-output.pid ms-monitor ":18245" 15 \
        </dev/null 2>&1 | rotatelogs $LOGDIR/ms-output_exporter-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
}

The process exporter treats '-' as minute operation for metric and not as prefix
name. What should be done is replace '-' with underscores, e.g.
reqmgr2ms_monitors()
{
    # start reqmgr2ms exporter
    wait4proc "reqmgr2ms" # check for pattern that it is running
    process_monitor.sh /data/srv/state/reqmgr2ms/ms-transferor.pid ms_transferor ":18247" 15 \
        </dev/null 2>&1 | rotatelogs $LOGDIR/ms-transferor_exporter-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
    process_monitor.sh /data/srv/state/reqmgr2ms/ms-monitor.pid ms_monitor ":18248" 15 \
        </dev/null 2>&1 | rotatelogs $LOGDIR/ms-monitor_exporter-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
    process_monitor.sh /data/srv/state/reqmgr2ms/ms-output.pid ms_output ":18245" 15 \
        </dev/null 2>&1 | rotatelogs $LOGDIR/ms-output_exporter-%Y%m%d-`hostname -s`.log 86400 >/dev/null 2>&1 &
}

I also changed in above section ms-monitor (which was used twice to ms_monitor and ms_output).

Therefore I suggest that you check manage script and replace '-' in
process_monitor.sh arguments with underscores. The syntax should be

process_monitor.sh /path_to_pid <pattern> ":PORT" <interval>

where pattern should NOT contain the '-'.

Valentin.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

After applying this fix, the errors are gone. But again reqmgr2ms_exporter service is NOT RUNNING. 

Thanks

**Comment by vkuznet** [comment]
Muhammad,
this time it is flaw in exporters manage script. Here is what you have
```
    vocms0742 )
        # das2go, mongodb, couchdb and reqmgr2ms exporter
        process_status "couchdb_exporter"
        process_status "das2go_exporter"
        process_status "mongodb_exporter"
        process_status "reqmgr2ms_exporter"
```
And process_status function is the following:
```
process_status()
{
    local pid=`ps auxw | grep "$1" | grep -v grep | grep -v rotatelogs | awk 'BEGIN{ORS=" "} {print $2}'`
    if [ ! -z "${pid}" ]; then
        echo $echo_e "$1 service is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID=${pid}"
        ps -f -wwww -p ${pid}
    else
        echo $echo_e "$1 service is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}"
    fi
}
```

So, the
```
process_status "reqmgr2ms_exporter"
```
is looking for "reqmgr2ms_exporter" pattern in ps output and it does not exists.

What exists is
```
root     19022  0.0  0.0 225756  4740 pts/1    Sl   17:29   0:00 process_exporter -pid 6593 -prefix ms_monitor -address :18248
root     19023  0.0  0.0 298080  4624 pts/1    Sl   17:29   0:00 process_exporter -pid 7347 -prefix ms_output -address :18245
root     19030  0.0  0.0 225756  4808 pts/1    Sl   17:29   0:00 process_exporter -pid 5955 -prefix ms_transferor -address :18247
```
and, therefore if you want to get status of reqmgr2ms exporters you should have
process_status "ms_monitor"
process_status "ms_output"
process_status "ms_transferor"
instead of
process_status "reqmgr2ms_exporter"
because you don't run reqmgr2ms_exporter you run process_exporter with different
patterns.

Please properly adjust manage script and redeploy.

Valentin.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Got it working now. Thanks.

```
[cmsweb@vocms0742 exporters]$ sudo bashs -l -c "/data/srv/current/config/exporters/manage status 'I did read documentation'"
node_exporter service is RUNNING, PID=25590
UID        PID  PPID  C STIME TTY          TIME CMD
root     25590     1  0 17:48 pts/0    00:00:00 node_exporter --web.listen-address=:19000
couchdb_exporter service is RUNNING, PID=25625
UID        PID  PPID  C STIME TTY          TIME CMD
root     25625     1  0 17:48 pts/0    00:00:00 couchdb_exporter -couchdb.uri=http://localhost:5984 -logtostderr=true -databases=reqmgr_workload_cache,reqmgr_config_cache,acdcserver,reqmgr_auxiliary -databases.views=false -telemetry.address=:15984
das2go_exporter service is RUNNING, PID=25602
UID        PID  PPID  C STIME TTY          TIME CMD
root     25602     1  0 17:48 pts/0    00:00:00 das2go_exporter -address :18217
mongodb_exporter service is RUNNING, PID=25614
UID        PID  PPID  C STIME TTY          TIME CMD
root     25614     1  0 17:48 pts/0    00:00:00 mongodb_exporter -mongodb.uri mongodb://localhost:8230 --web.listen-address :18230 -groups.enabled
ms_monitor service is RUNNING, PID=25638 25698
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root     25638     1  0 17:48 pts/0    S      0:00 /bin/bash /data/srv/beHG2005d/sw/slc7_amd64_gcc630/cms/exporters/0.1.4/bin/process_monitor.sh /data/srv/state/reqmgr2ms/ms-monitor.pid ms_monitor :18248 15
root     25698 25638  0 17:48 pts/0    Sl     0:00 process_exporter -pid 6593 -prefix ms_monitor -address :18248
ms_output service is RUNNING, PID=25641 25699
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root     25641     1  0 17:48 pts/0    S      0:00 /bin/bash /data/srv/beHG2005d/sw/slc7_amd64_gcc630/cms/exporters/0.1.4/bin/process_monitor.sh /data/srv/state/reqmgr2ms/ms-output.pid ms_output :18245 15
root     25699 25641  0 17:48 pts/0    Sl     0:00 process_exporter -pid 7347 -prefix ms_output -address :18245
ms_transferor service is RUNNING, PID=25636 25690
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root     25636     1  0 17:48 pts/0    S      0:00 /bin/bash /data/srv/beHG2005d/sw/slc7_amd64_gcc630/cms/exporters/0.1.4/bin/process_monitor.sh /data/srv/state/reqmgr2ms/ms-transferor.pid ms_transferor :18247 15
root     25690 25636  0 17:48 pts/0    Sl     0:00 process_exporter -pid 5955 -prefix ms_transferor -address :18247
```

best

**Comment by amaltaro** [comment]
Cool! Thanks, Valentin and Imran.

**Pull request merged**
