### PR TITLE
Changes to turn on authz for DAS

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by BrunoCoimbra** [comment]
Hey @vkuznet is this PR still valid?

**Comment by vkuznet** [comment]
Bruno, seems like we don't need this anymore since DAS auth is in place, how you implement it? May be I made another PR, I just don't remember

**Comment by BrunoCoimbra** [comment]
We did it trhough PR #352.

**Comment by vkuznet** [comment]
Closing the ticket since it was done in #352

**Pull request closed without merging**
