### PR TITLE
Adding forward rules for CRAB Schedds

### PR DESCRIPTION
**Pull request by todor-ivanov**

### CODE REVIEW

**Comment by h4d4** [comment]
@todor-ivanov Todor, 

I'm going to merge this PR, and apply it on testbed first.
I'll let you know once it is on testbed.

Best Regards, Lina.

**Comment by todor-ivanov** [comment]
@h4d4 Thanks  Lina!

**Comment by h4d4** [comment]
@todor-ivanov Todor, 

the rules are in testbed and it seems to work to me, for example: 
https://raw.githubusercontent.com/dmwm/deployment/master/frontend/backends-preprod.txt

One more thing, would you please provide me other PR, removing line:
[#L15](https://github.com/dmwm/deployment/blob/master/frontend/backends-preprod.txt#L15) for backends-preprod.txt, please see that the node was already the in line [#L23](https://github.com/dmwm/deployment/blob/master/frontend/backends-preprod.txt#L23)

Best Regards, Lina.

**Comment by todor-ivanov** [comment]
@h4d4 It is there. Thanks, again!

**Pull request merged**
