### PR TITLE
enable colz and phase-1 pixel map dressing for Phase1PixelV

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all, enables the coloring of 2D maps in the Phase-1 Pixel Validation folder.
Tested in a local GUI:
   * before this PR:

image

   * after this PR:
   
image

cc:
@sroychow @arossi83

### CODE REVIEW

**Comment by mmusich** [comment]
@jfernan2 FYI

**Comment by jfernan2** [comment]
@muhammadimranfarooqi  this can be also included in the same shot as #1047 and #1048 
Thanks

**Comment by muhammadimranfarooqi** [comment]
@mmusich 
Could you please confirm this PR is ready for deployment in production environment. Thanks

**Comment by mmusich** [comment]
@muhammadimranfarooqi confirmed. Thank you.

**Pull request merged**
