### PR TITLE
Updating strip and pixel shift layouts

### PR DESCRIPTION
**Pull request by fioriNTU**
Including all the plots to be checked by Tracker Offline shifters in the corresponding shift layout.
Adding a plot missing to SiStrip layout

### CODE REVIEW

**Comment by pphogat** [comment]
@fioriNTU, In dqmgui/layouts/sistrip_T0_layouts.py line 342: it's written as versuls. I think you would like to write versus. Same mistake in dqmgui/layouts/shift_sistrip_T0_layout.py line 137.

Thanks,
Priyanka and Tomas for DQM

**Comment by fioriNTU** [comment]
@pphogat I will fix asap and commit the change, thanks for spotting this!

**Comment by threus** [comment]
thanks @fioriNTU

**Comment by threus** [comment]
@h4d4 , Tests are OK. Could you please merge this?
Thanks,
Tomas for DQM

**Pull request merged**
