### PR TITLE
New Tracker Alignment Workspace for Offline DQM GUI

### PR DESCRIPTION
**Pull request by dmeuser**
This is the first PR to add a new tracker alignment workspace to the offline DQM.
The PR includes the following:
- Adding a new alignment workspace in `dqmgui/workspaces-offline.py`
- Adding additional layouts showing mainly different representation of residual plots in ` dqmgui/layouts/pixelPhase1_T0_layouts.py`
- Adding lines to several pixel 2D profile plots in `dqmgui/style/SiPixelMapsRenderPlugin.cc`

The PR was tested with the `HG2011a` tag and a private data sample on a private DQM GUI. For now  the private GUI can be found by using `ssh -NL 8080:localhost:8080 <username>@lxplus751.cern.ch` and then following this link https://tinyurl.com/yb95bad5.

The new workspace/layouts show histograms which became available by the following CMSSW PR: https://github.com/cms-sw/cmssw/pull/29355

@arossi83 @mmusich

### CODE REVIEW

**Comment by sroychow** [comment]
Hi @jfernan2, we have checked the display in the private GUI and it looks okay for us. 
Thanks @dmeuser !!!

**Comment by jfernan2** [comment]
@muhammadimranfarooqi 
This PR is ready for merging. Thanks

**Comment by muhammadimranfarooqi** [comment]
@dmeuser @jfernan2 

This PR has been deployed in cmsweb-testbed.cern.ch. Please provide validation results at this ticket.

https://gitlab.cern.ch/cms-http-group/doc/-/issues/240

Thanks

**Comment by jfernan2** [comment]
Thanks @muhammadimranfarooqi 
Yes, I see Alignment workspace in DQM offline test machine vocms0731
https://cmsweb.cern.ch/dqm/offline-test/

**Pull request merged**
