### PR TITLE
Change pid to procpid since pid is reserved activity keyword

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Comment by amaltaro** [comment]
Given that the ServerMonitor is used in the whole cluster for monitoring all CMSWEB services, let's be careful with these changes and make sure we understand what we are changing.
Besides that, can I ask you both to a) squash commits to make the history cleaner and b) properly test these things. Thanks (sorry for being grumpy, but I see  a frantic mode of making and pushing changes.)

**Comment by vkuznet** [comment]
Adjusted, squashed, tested. Here is output from my DBS pod:
Mar 31 17:36:34 dbs SYSTEM PROCESSES: 2, PROCPID 26849 26857, CPU: 0.0%, MEM: 0.3%, FILES: 0, OOMSCORE: 2002, OOMADJ: 2002, OOMSCOREADJ: 2000, SWP: 0.0%, THREADS: 36, USER: 8.15, SYSTEM: 1.95, RSS: 103960576, VMS: 951832576, SWAP: 0

The SYSTEM PROCESSES reports first number of process it monitors, in this case 2. Then it will print PIDs of the processes and sum of all requested metrics. Please note that oomscore (and others) is a sum of individual values of monitored processes.

In my case I tested with single monitoring.ini file, but Yuyi already implemented individual monitoring ini files for individual DBS instances.

**Comment by yuyiguo** [comment]
@vkuznet 
Valentin,
Here is the test from my side.
1. checked out from the head of dmwm/deployment
2. applied patch 747 and 748. 
"git apply /tmp/747.patch --check"  and  "git apply /tmp/748.patch --check"  did not work so I did below. When I patched with 747, I got some code rejected [3]. So I applied the rejected code manually.
```
curl -L -k https://github.com/dmwm/deployment/pull/747.patch > /tmp/747.patch
curl -k -L https://github.com/dmwm/deployment/pull/748.patch >/tmp/748.patch
patch -p1 < /tmp/747.patch 
patch -p1 </tmp/748.patch
```
However, in the server-monitor-20190331.log, I no longer see "_dbs SYSTEM PROCESSES " as shown in [2]. What I got were [1]. Not sure what I missed here?
Thanks,
Yuyi

```
[1]
Apr 01 00:37:41 frontend URLREPORT url:<http://localhost/server-status?notable>: ('localhost', '/server-status HTTP/1.1')
Apr 01 00:37:41 frontend URLREPORT url:<http://localhost/server-status?notable>: ('localhost', '/server-status?notable HTTP/1.1')
Apr 01 00:37:41 frontend URLREPORT url:<http://localhost/server-status?notable>: ('localhost', '/server-status?notable HTTP/1.1')
Apr 01 00:37:41 frontend URLREPORT url:<http://localhost/server-status?notable>: ('localhost', '/server-status HTTP/1.1')
Apr 01 00:37:41 frontend URLREPORT url:<http://localhost/server-status?notable>: ('::1', '/server-status?notable HTTP/1.1')
Apr 01 00:37:41 globalR PING OK <http://localhost:8252/dbs/>
Apr 01 00:37:41 phys03W PING OK <http://localhost:8255/dbs/>
Apr 01 00:37:41 phys03R PING OK <http://localhost:8254/dbs/>
Apr 01 00:37:41 mgt PING OK <http://localhost:8251/>
Apr 01 00:37:41 globalW PING OK <http://localhost:8253/dbs/>
Apr 01 00:37:41 frontend PING OK <http://localhost/server-status>
Apr 01 00:37:41 dbs PING OK <http://localhost:8250/dbs/>
Apr 01 00:37:41 dbsmigration PING OK <http://localhost:8251/>
Apr 01 00:37:41 mgt PROCESS pid:22158
Apr 01 00:37:41 dbsmigration PROCESS pid:22359
Apr 01 00:37:41 frontend PROCESS pid:22455
Apr 01 00:37:41 frontend PROCESS pid:22678
Apr 01 00:37:41 frontend PROCESS pid:22679
Apr 01 00:37:41 frontend PROCESS pid:22680
Apr 01 00:37:41 frontend PROCESS pid:22681
Apr 01 00:37:41 frontend PROCESS pid:22682
Apr 01 00:37:41 phys03W PROCESS pid:22152
Apr 01 00:37:41 phys03R PROCESS pid:22144
Apr 01 00:37:41 globalR PROCESS pid:22128
Apr 01 00:37:41 globalW PROCESS pid:22133
Apr 01 00:37:41 dbs PROCESS pid:22120
```

```
[2]
Mar 29 19:11:19 _dbs SYSTEM IGNORE failed to get files field information: psutil.AccessDenied (pid=6247)
Mar 29 19:11:19 _dbs SYSTEM PROCESSES: 1, CPU: 0.1%, MEM: 0.8%, FILES: 0, OOMSCORE: 4, OOMADJ: 0, OOMSCOREADJ: 0, SWP: 0.0%, THREADS: 18, USER: 89.66, SYSTEM: 18.06, RSS: 124579840, VMS: 551985152, SWAP: 1986560
```
```
[3]
--- admin/ServerMonitor
+++ admin/ServerMonitor
@@ -218,30 +244,15 @@
         elif field == 'io':
           addfield(data, field, safefield('io', proc.io_counters))
         elif field == 'files':
-          addfield(data, field, safefield('files', proc.open_files))
-        elif field == 'pid':
-          addfield(data, field, safefield('pid', proc.pid))
+          addfield(data, field, ofiles)
+        elif field == 'procpid':
+          addfield(data, field, proc_pid)
         elif field == 'oomscore':
-          try:
-              with open('/proc/%s/oom_score' % proc.pid) as fdesc:
-                  oom_score = int(fdesc.read().replace('\n', ''))
-                  addfield(data, field, oom_score)
-          except:
-            addfield(data, field, 0)
+          addfield(data, field, oom_score)
         elif field == 'oomadj':
-          try:
-              with open('/proc/%s/oom_adj' % proc.pid) as fdesc:
-                  oom_adj = int(fdesc.read().replace('\n', ''))
-                  addfield(data, field, oom_adj)
-          except:
-            addfield(data, field, 0)
+          addfield(data, field, oom_score)
         elif field == 'oomscoreadj':
-          try:
-              with open('/proc/%s/oom_score_adj' % proc.pid) as fdesc:
-                  oom_score_adj = int(fdesc.read().replace('\n', ''))
-                  addfield(data, field, oom_score_adj)
-          except:
-            addfield(data, field, 0)
+          addfield(data, field, oom_score_adj)

     if data['processes'] < 1:
       return
~                            
```

**Comment by vkuznet** [comment]
Yuyi,
It seems to me that you applied patch to a tree with other patches since I made
it clean against the master head and I don't see any errors.

Here is how I do it, first I check the patch itself for errors
```
patch -p1 --dry-run < 747.patch
patching file admin/ServerMonitor
```
and then if there is no errors I apply it
```
patch -p1 < 747.patch
patching file admin/ServerMonitor
```

Regarding not seeing output. Can you try DO NOT apply 748 patch and report here.
I'll check with Lina today and hope she will report her findings as well here.

**Comment by vkuznet** [comment]
Yuyi,
another thought on why you don't see output. Did you changed your
monitoring*.ini files? Now you should lists procpid in PROCESS_ACTIVITY
instead of pid, e.g. here is what I have:
```
PROCESS_ACTIVITY="procpid,cpu,mem,files,oomscore,oomadj,oomscoreadj,swp,threads,user,system,rss,vms,swap"
```

**Comment by yuyiguo** [comment]
Valentin, LIna,

I have release at FNAL today, I will look into this later.
Thanks,
Yuyi

**Comment by yuyiguo** [comment]
Valentin,

I checked out deployment head that you already applied patch 747 and related patches, except for patch 748. Below is my test without patch 748. "AccessDenied" may related to not running the job as root? I will apply patch 748 to see if this will go away.
Thanks,
Yuyi
```
Apr 04 00:10:39 ADMIN FAILURE TASK ('_dbs', True, 'Root.py.*[/]DBSMigrate.*.py', ['procpid', 'cpu', 'mem', 'files', 'oomscore', 'oomadj', 'oomscoreadj', 'swp', 'threads', 'user', 'system', 'rss', 'vms', 'swap']) ERROR: psutil.AccessDenied (pid=29968)
Apr 04 00:10:39 ADMIN FAILURE Traceback (most recent call last):
Apr 04 00:10:39 ADMIN FAILURE   File "/data/srv/current/config/admin/ServerMonitor", line 90, in run
Apr 04 00:10:39 ADMIN FAILURE     self._do(*task)
Apr 04 00:10:39 ADMIN FAILURE   File "/data/srv/current/config/admin/ServerMonitor", line 177, in _do
Apr 04 00:10:39 ADMIN FAILURE     ofiles = len(proc.open_files())
Apr 04 00:10:39 ADMIN FAILURE   File "/data/srv/HG1904d/sw.yuyi/slc7_amd64_gcc630/external/py2-psutil/5.4.5-comp/lib/python2.7/site-packages/psutil/__init__.py", line 1133, in open_files
Apr 04 00:10:39 ADMIN FAILURE     return self._proc.open_files()
Apr 04 00:10:39 ADMIN FAILURE   File "/data/srv/HG1904d/sw.yuyi/slc7_amd64_gcc630/external/py2-psutil/5.4.5-comp/lib/python2.7/site-packages/psutil/_pslinux.py", line 1405, in wrapper
Apr 04 00:10:39 ADMIN FAILURE     raise AccessDenied(self.pid, self._name)
Apr 04 00:10:39 ADMIN FAILURE AccessDenied: psutil.AccessDenied (pid=29968)
```

**Pull request merged**
