### PR TITLE
Changing WMCORE_ROOT to T0_ROOT since both WMCore and T0 are merged i…

### PR DESCRIPTION
**Pull request by vytjan**
…nto one wmagent subsystems.
Do not merge it yet as it is supposed to go together with
https://github.com/dmwm/WMCore/pull/9173

### CODE REVIEW

**Comment by vytjan** [comment]
@amaltaro following the https://github.com/dmwm/WMCore/pull/9173 , this can be merged as well as both PRs were tested together.
Then I will proceed with a new T0 release on https://github.com/cms-sw/cmsdist/pull/4975

**Comment by amaltaro** [comment]
Ok Vytas, but I don't merge anything on this repository :)
@h4d4 Lina, can you please merge this PR for Vytas? Thanks

**Comment by h4d4** [comment]
@vytjan @amaltaro 

Alan, Vytas, it was merged.

Best Regards, Lina.

**Comment by vytjan** [comment]
Thanks @amaltaro @h4d4 Alan, Lina!

**Pull request merged**
