### PR TITLE
Define MSOutput policy for RelVal; remove legacy tapePledges

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes https://github.com/dmwm/WMCore/issues/10106

plus, remove the obsolete `tapePledges` attribute.

### CODE REVIEW

**Comment by haozturk** [comment]
@amaltaro  thanks a lot for providing these changes. I have a question: what happens when there are more than 1 destination such as GEN-SIM in this case?

Right now, everything should go to CERN, so I think we should remove FNAL in this PR unless @bbilin has an objection.

**Comment by bbilin** [comment]
https://github.com/dmwm/WMCore/pull/11024

I just wrote exact same suggestion here.

I agree that FNAL shall be droped.

**Comment by amaltaro** [comment]
> @amaltaro thanks a lot for providing these changes. I have a question: what happens when there are more than 1 destination such as GEN-SIM in this case?

@haozturk that's a good question though. I see I could change the WMCore code to make number of copies to be a function of the destinations. So, if someone decides FNAL and CERN - as it is right now - then the Rucio rule should target both destinations but ask for 2 copies instead of only 1. Does this make sense?

Thanks for your input. I am going to remove FNAL from the policy configuration.

**Comment by haozturk** [comment]
> So, if someone decides FNAL and CERN - as it is right now - then the Rucio rule should target both destinations but ask for 2 copies instead of only 1. Does this make sense?

If there is going to be multiple destination feature, I think it's better to ask for a separate copy at every provided location instead of letting Rucio to pick one. It's more explicit. With that, I think we'll not use that feature for the near future, but IMO it's good to have it in case. We should update the documentation about this change. It can be easily confusing.

**Pull request merged**
