### PR TITLE
Updating frontend rules for k8s cluster

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by amaltaro** [comment]
I'd say all these lines are already covered in the backends mapping, e.g.:
```
 ^/auth/complete/(?:couchdb/acdcserver|acdcserver)(?:/|$) vocms0742.cern.ch :affinity
```

there is an or over there, so this line should match:
```
 ^/auth/complete/couchdb/acdcserver
 ^/auth/complete/acdcserver
```

Have you tested these changes?

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

Yes, you are right. I only needed changes in VMs redirection rules here https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/preprod/frontend/vms

I have updated this PR. 

Cheers

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , the PR contains changes to httpsgo while you're discussing couchdb related apps. Did you commit your changes?

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Initially, I had put rules for couch but after testing with Alan's suggestions, I removed those with new commits. Now only httpgsgo rule is there.

**Pull request merged**
