### PR TITLE
add ES front-end information to top level layouts

### PR DESCRIPTION
**Pull request by cmkuo**
add ES front-end electronics (gain) information to top level layouts

### CODE REVIEW

**Comment by vanbesien** [comment]
Ping

**Comment by cmkuo** [comment]
@vanbesien sorry that I am not a git expert. 
it seems to me the problem is this PR contains the changes from last summer. 
should I start from scratch and make a new PR ?

**Comment by vanbesien** [comment]
Hey yes, before you do this with git, always make sure you first pull in the latest version of the master branch and then start from there.
You have some options:
- Get latest version of the master branch and just do the changes again - if there are not too many
- Get latest version, cherrypick the commits of this PR on top of them and solve the merge conflicts
- Rebase this PR

**Comment by cmkuo** [comment]
@vanbesien ok, I tried to checkout from the one I forked.
git clone https://github.com/cmkuo/deployment.git
However, I found it's not up-to-date. Should I fork it again ?
If not, how can I update it to latest version ?

**Comment by vanbesien** [comment]
Hey, you make a fork one time and then you basically never care about it anymore and there is no point in trying to update it. Your fork is just your personal area to which you can push your branches before you make a PR.

You should always pull the master from the main "Deployment" repository and then create a branch from it and push that branch to your private fork of Deployment. And then from that one you can create the PR.

**Pull request closed without merging**
