### PR TITLE
Remove acdcserver cleanup cronjob

### PR DESCRIPTION
**Pull request by amaltaro**
Cleanup of ACDC couch docs is taken care by a ReqMgr2 thread (for quite some time already), thus there is no need to keep this - broken - configuration/cronjob around.
@ticoann please review

### CODE REVIEW

**Comment by amaltaro** [comment]
Changes tested and it looks good. However, I don't think we need to run another deployment to get this change in. It can wait the cmsweb production upgrade IMO.

**Comment by ticoann** [comment]
Yes that would be fine. Thanks Alan.

**Comment by amaltaro** [comment]
You can either merge it now or after the cmsweb upgrade. Either way is fine for me.

**Comment by h4d4** [comment]
@amaltaro @ticoann 
Thanks for the feedback! merged.

**Pull request merged**
