### PR TITLE
Adjustements to the tracker layout on RelVal

### PR DESCRIPTION
**Pull request by arossi83**
Update on the Tracker DQM layout on RelVal

### CODE REVIEW

**Comment by fioriNTU** [comment]
@h4d4 this PR is fine for the DQM, could you please merge it and deploy at the next CMSWEB upgrade?

**Comment by h4d4** [comment]
@fioriNTU @schneiml Hello fioriNTU,

before merge it I'd like to confirm with Marcel if all you DQM guys are agree with those changes?
Once I've got confirmation I'll merge it. The changes should be deployed during next week.

Best Regards, Lina.

**Comment by h4d4** [comment]
@rovere @schneiml @fioriNTU 

Dear DQM team, 

I'd like to confirm that all you are agree with the merging request for this PR.

Thanks!

Best Regards, Lina.

**Comment by schneiml** [comment]
@h4d4 The changes look safe to me, and I assume Alessandro tried them locally to see that they work as expected.

You can go ahead and merge them.

**Comment by fioriNTU** [comment]
@h4d4 I personally saw the result in a private RelVal GUI, there should be no problems in merging this

**Comment by h4d4** [comment]
@schneiml @rovere @fioriNTU 

Thanks to all for the feedback, sorry for be picky with this PR but since is the first time that I got a PR request from fioriNTU and I don't know him, is better ask.

Once, I run next tested deployment I'l let you know.
Best Regards, Lina.

**Comment by fioriNTU** [comment]
@h4d4 sorry for not introducing myself before, I am Francesco Fiori, one of the three DQM conveners.

**Comment by h4d4** [comment]
@fioriNTU Francesco, 

thanks for let me know it, so the PR was was deployed in tetsbed.
Please remind to make a feed-back in this [ticket](https://gitlab.cern.ch/cms-http-group/doc/issues/155)
just saying that the change is ready to go to production.

Best Regards, Lina

**Pull request merged**
