### PR TITLE
Updates on GEM onlineDQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR updates and extends the part of onlineDQM for GEM. The details are following: 

 - Rearranged the status plots to adjust the change of GEM DAQ
 - Rearranged most of plots to be more convenient

This PR is related to PRs on cms-sw; see 
https://github.com/cms-sw/cmssw/pull/34614 (to master)
https://github.com/cms-sw/cmssw/pull/34782 (backport)

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@quark2 
Is this PR ready for deployment? It includes old commits.

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi, 
I've checked that (except one line) the final changes are desired only as for the new version. Then is it okay to merge?

**Comment by quark2** [comment]
But is it better to make a new PR with cleaner commits and close it...?

**Comment by muhammadimranfarooqi** [comment]
@quark2 
If changes are Ok then there is no need to create new PR. I can squash commits and merge.

**Comment by quark2** [comment]
@muhammadimranfarooqi 
The changes are all okay now. Thanks!

**Pull request merged**
