### PR TITLE
change manage and config script

### PR DESCRIPTION
**Pull request by ticoann**
@vkuznet, please review.

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, Hi Valentin,

Where is this file(unifiedConfiguration.json)?

https://github.com/ticoann/deployment/blob/dbd048e1d4ae641a73a660818bb6ddbdd81058c8/reqmgr2ms/manage#L49

I don't see in the repository.
https://github.com/dmwm/deployment/tree/master/reqmgr2ms

**Comment by ticoann** [comment]
I used https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/config.json
but isn't that supposed to be in the deployment directory?

**Comment by ticoann** [comment]
Anyway, I think I will move that to AUX db as well if that is OK.

**Comment by vkuznet** [comment]
Seangchan,
I think I never put it into deployment/reqmgr2ms. But we do have "default"
config in
https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/MicroService/Unified
see
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Common.py#L37
The file is
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/config.json
I think we should move it to deployment/reqmgr2ms though.
Best,
Valentin.

**Pull request merged**
