### PR TITLE
Offline DQM update of Pixel/Strip/Tracking folders

### PR DESCRIPTION
**Pull request by Payal7890**
We have added/removed/moved few plots of Offline DQM GUI
from PixelPhase1/SiStrip/Tracking workspaces (Quick
Collection and Layouts) to make the certification work easier.
We tested the changes in the private GUI prova1234, using
runs 380066 and 380074.
To connect to the private GUI outside of CERN network:
tunneling (and proxy in browser, with same port number) are
needed:
ssh -D &lt;port number&gt; CERNUSERNAME@lxplus.cern.ch
We hereby attach the tinyURL links before (Official, GUI) and
after the changes (New, prova1234 GUI)

1) PixelPhase1 (Layouts):
Original: https://tinyurl.com/2axa37o2
New: https://tinyurl.com/4w4jrn5w

2) PixelPhase 1 (Quick Collection):
Original:  https://tinyurl.com/2bvqgfzj
New:  https://tinyurl.com/4uhnpv94

3) SiStrip (Layouts):
Original: https://tinyurl.com/23vn9w24
New:  https://tinyurl.com/mr2n6xt3

4) SiStrip (Quick Collection):

Original:  https://tinyurl.com/2bgm5z9n
New:  https://tinyurl.com/bddv26ea

5) Tracking (layouts)
Original:  https://tinyurl.com/29fk7gw5
New: https://tinyurl.com/yfya69se

6) Tracking (Quick Collection)
Original: https://tinyurl.com/27cx5emc
New: https://tinyurl.com/mr35pyba

### CODE REVIEW

**Comment by nothingface0** [comment]
Dear @Payal7890,

We have deployed the changes on a test machine. You can see them [here](https://cmsweb-test4.cern.ch/dqm/offline-test/start?runnr=381478;dataset=/ScoutingPFMonitor/Tier0_REPLAY_2024-PromptReco-v4085754/DQMIO;sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=PixelPhase1;size=M;root=PixelPhase1/Layouts;focus=;zoom=no;). Can you verify that they look as expected?

**Comment by alaperto** [comment]
Hi @nothingface0 , is it possible to have ZeroBias dataset?
Everything looks OK, but the Strip Residuals plots are not found (nothing was changed in the code for those plots).
SiStrip Layouts Residual pots missing

**Comment by alaperto** [comment]
Sorry, did not notice that many runs and samples were available.
I found ZeroBias and Residual plots are there, as expected.

We'll just wait another week to receive comments, than (if there are no comments) this could be deployed in July.

SiStrip Residuals plots

**Comment by alaperto** [comment]
Hi @nothingface0 , the changes are as expected.
Since no-one else requested any modification (despite the several requests for feedback), can you move this to production?

Thanks,
Alessandro

**Comment by nothingface0** [comment]
Thanks for verifying @alaperto. We are in the process of migrating the DQMGUI machines to a new OS, so we will try to apply it to production with @arooshap ASAP.

**Pull request merged**
