### PR TITLE
GEM online DQM updates

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR updates and extends the part of onlineDQM for GEM. The details are following: 

 - Most of plots in the Quick collection page is removed but compressed plots are provided
 - Detailed plots for each chambers are moved into directories

This PR is related to PRs on cms-sw; see 
https://github.com/cms-sw/cmssw/pull/32792 (to master)
https://github.com/cms-sw/cmssw/pull/32791 (backport)

For more detail, please see [this](https://indico.cern.ch/event/1003303/contributions/4213103/subcontributions/327221/attachments/2181400/3684982/20210201_GEM_RC_GEM_OnlineDQM.pdf) to check more details

@jshlee @watson-ij

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@quark2 

Don't you need to have any PR in `cmsdist` repository for these changes? Is this PR is ready to merge? Thanks

**Comment by muhammadimranfarooqi** [comment]
@quark2 

Could you please reply to the above comment. Thanks

**Comment by muhammadimranfarooqi** [comment]
@quark2 

I did not hear back from you regarding this PR. Do you want to include it in next month release or not? please comment. Thanks

**Comment by quark2** [comment]
Hi @ muhammadimranfarooqi, 

Sorry for my super late response...
Actually I have no idea about `cmsdist`... But my colleague advised that I had to mail to T0. Could you inform about that?
Btw this PR is already reported in a DQM General meeting [1]. Hope it is useful.

Best regards, 
Byeonghak Ko

[1] https://indico.cern.ch/event/1005033/#12-simplification-of-online-dq

**Comment by muhammadimranfarooqi** [comment]
@quark2 

I am including this PR then. I dont' attend GEM DQM general meetings. Any specific request for deployment in cmsweb should be made accordingly.

**Comment by quark2** [comment]
@muhammadimranfarooqi 

Ahh, yep I should do so... Many thanks!

Best regards, 
Byeonghak Ko

**Comment by muhammadimranfarooqi** [comment]
@quark2 

I have deployed this PR in http://cmsweb-testbed.cern.ch cluster. Please test and provide validation results at this ticket https://gitlab.cern.ch/cms-http-group/doc/-/issues/253

**Comment by muhammadimranfarooqi** [comment]
@quark2 

Have you tested this PR in the testbed ?

**Comment by muhammadimranfarooqi** [comment]
@quark2 

Despite sending you messages about validation results, I did not get any reply from you regarding this PR. As Tuesday 2nd March is production upgrade, I'll remove this PR from deployment in the production nodes if I don't hear anything from you regarding validation results by Monday morning.

**Comment by muhammadimranfarooqi** [comment]
@quark2 

I have already created revert PR for this which will remove these changes after merging it.

**Comment by quark2** [comment]
Sorry for my forget of reply...

But also I had no idea how to do when I got your reply after the merge. I found that there is nothing I can do but just watch all the GEM onlineDQM GUI are working as desired. How can I test it in the testbed? I tried to find an instruction for that but I cannot. Or, just reporting everything is fine/something is weird is all of what I should do?

Best regards, 
Byeonghak Ko

**Comment by muhammadimranfarooqi** [comment]
@quark2 

You can test it on the testbed cluster https://cmsweb-testbed.cern.ch. This is relevant URL https://cmsweb-testbed.cern.ch/dqm/dev/

**Comment by quark2** [comment]
You mean upload any GEM DQM root file into https://cmsweb-testbed.cern.ch/dqm/dev/ (by visDQMUpload) and check if the GUI shows everything well?
Btw the site in the link looks like an offlineDQM, not an onlineDQM. Is it okay?

Best regards, 
Byeonghak Ko

**Comment by quark2** [comment]
And also I checked all of Online, Online-playback, Online-test in https://cmsweb-testbed.cern.ch/ and GEM GUI is working well, as I mentioned.

**Comment by muhammadimranfarooqi** [comment]
@quark2 

Well, yes this is offlineDQM. I don't know how it can be testbed. Currently, this PR is deployed in this node only.

**Comment by quark2** [comment]
Then... what should I do? I mean, where should I upload my DQM plots and check if it is okay or not?

**Comment by muhammadimranfarooqi** [comment]
I don't know how to test it. CMSWEB only provides the infrastructure to deploy and run services. How to test services is the developer's responsibility. You may ask DQM folks about this.

**Comment by quark2** [comment]
Okay, then what should I show for the validation?

Actually I saw that all GEM onlineDQM plots from MWGR No. 1 in 2021 are displayed in the P5 onlineDQM during the run and the desired plots are also found in all onlineDQM sites (Online, Online-playback, Online-test) in https://cmsweb-testbed.cern.ch/, and then I thought it was enough. But it seems like I have to show something more.

**Comment by muhammadimranfarooqi** [comment]
@quark2 

You don't need to show me anything. Just confirm that this PR is ready to deploy in the production nodes. Then, I'll deploy it.

**Comment by vkuznet** [comment]
Byeonghak, on cmsweb all service responsible should properly test their services before putting changes to production. How to test the service is up to dev team which responsible for it. It can be a simple test to query API, or more comprehensive suit of tests including remote/local API access, testing web interfaces. Everything is up to dev team to define. For CMSWEB operator, we should only say if it is ok or not to include new code to production release. You represent now DQM dev team and you should define your own set of tests and based on them just say if your new release is ok or not.

**Comment by quark2** [comment]
Hi @vkuznet, 

Well, I already tested in a local and private site and checked everything was okay, and also (sorry to mention it too frequently) saw the new version displays all plots well in sites (both central and testbed) in CMSWEB. I thought it would be enough to say that it is confirmed, but now I think I need to ask to DQM folks what I should do more in this stage to make sure everything. I'll ask and check more ASAP.

Best regards, 
Byeonghak Ko

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi, 

I found that I already have confirmations in the level of DQM dev team. The updates are presented in [1] and DQM dev team already tested and confirmed the updates. If you want, I can forward the mail about that. I asked again to DQM dev team and have got that it is enough for the confirmation. Sorry for this late.

Best regards, 
Byeonghak Ko

**Comment by muhammadimranfarooqi** [comment]
Hi @quark2 
thanks for confirmation. I'll include this PR in production upgrade. Cheers

**Comment by quark2** [comment]
Thanks a lot! I should ask and make sure about that earlier...

Best regards, 
Byeonghak Ko

**Pull request merged**
