### PR TITLE
New plots on GEM online DQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR updates and extends the part of onlineDQM for GEM. The details are following: 

 - Additional plots displaying summarized VFAT status
 - recHit wheel occupancy

This PR is related to PRs on cms-sw; see 
https://github.com/cms-sw/cmssw/pull/33767 (to master)
https://github.com/cms-sw/cmssw/pull/33768 (backport)

For more detail, please see [this](https://indico.cern.ch/event/1039414/contributions/4365943/subcontributions/338621/attachments/2245637/3808249/20210517_GEM_RC_DQM.pdf) to check more details

@jshlee @watson-ij @seungjin-yang

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@quark2 

Is it ready to deploy in testbed?

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi, 

yep, I'm ready for the testbed.
(FYI, you can check the result in http://cms.sscc.uos.ac.kr:50100/dqm/online-dev/, run 341169.)

**Comment by seungjin-yang** [comment]
@muhammadimranfarooqi hi, can I add more commits to this PR for updating GEM offline DQM?

**Comment by muhammadimranfarooqi** [comment]
@seungjin-yang 

Yes, as long as this is not merged, you can add more commits.

**Comment by seungjin-yang** [comment]
@muhammadimranfarooqi Hi, this PR is ready for deployment in both online and offline testbeds.

**Comment by muhammadimranfarooqi** [comment]
@quark2 

This PR has been deployed in cmsweb-testbed cluster. Please test and confirm its readiness for production cluster.

**Comment by seungjin-yang** [comment]
@muhammadimranfarooqi I confirmed that the updated ***offline*** DQM GUI works well.

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi, 

All other changes on this PR seem deployed into cmsweb-testbed, except the change in the commit c41daea which is for the **_online_** DQM GUI. Could you check it?

Best regards, 
Byeonghak Ko

**Comment by muhammadimranfarooqi** [comment]
@quark2 

It exists here in https://github.com/dmwm/deployment/blob/master/dqmgui/workspaces-online.py#L409

**Comment by quark2** [comment]
@muhammadimranfarooqi 

Yep, the commit is merged well into the master branch of this repository. But the newest codes seem not deployed into the onlineDQM in the cmsweb-testbed.

**Comment by muhammadimranfarooqi** [comment]
@quark2 

I don't deploy in onlineDQM. I deploy only in `vocms0731` which is testbed node and `vocms0738`, `vocms0739` which are production nodes. 

You may ask relevant person who is responsible for onlineDQM as this VM is at P5 network.

**Comment by quark2** [comment]
@muhammadimranfarooqi

I see. Sorry for bothering you... I'll notice when the test is done.

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi 

We requested the test to DQM core developer team and we have confirmed that all codes are deployed well into the cmsweb. ([1])

[1] https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=GEM;size=M;root=Quick%20collection;focus=GEM/recHit/rechit_wheel_GE-11_L1;zoom=no;

**Comment by muhammadimranfarooqi** [comment]
Thanks @quark2 for informing me.

**Pull request merged**
