### PR TITLE
Use full path to DBS cfg files

### PR DESCRIPTION
**Pull request by vkuznet**
Replacement of #793

### CODE REVIEW

**Comment by yuyiguo** [comment]
@vkuznet 
Valentin,

You would need to remove the $CFGDIR of $CFGDIR/$1 in stop_dbs() and status_db() functions too.

**Comment by vkuznet** [comment]
That's right, I submitted necessary changes. Please review again.

**Comment by yuyiguo** [comment]
It looked good to me now @vkuznet .

**Comment by vkuznet** [comment]
Yuyi, in that case please schedule it fo next cmsweb upgrade. I need the patch in development tree that I can build new RPMs with it.

**Comment by h4d4** [comment]
@yuyiguo Yuyi, 

In case that this PR is needed to be included in HG1908 release, 
please remind below ticket to ask for inclusions:
https://gitlab.cern.ch/cms-http-group/doc/issues/171

Best Regards, Lina.

**Pull request merged**
