### PR TITLE
Allow user to specify MYSQL socket file or use default

### LINKED ISSUE #184: Be able to specify the MySQL socket filename
Socket filenames (with path) in linux can be at most 117 characters long. Burying the socket file deep in the deployment can blow this limit. Instead, allow the socket file to be set by an optional environment variable.

### PR DESCRIPTION
**Pull request by ericvaandering**
Fixes #184. @ticoann @geneguvo please review

### CODE REVIEW

**Comment by ticoann** [comment]
Hi Eric, So DBSOCK will be separately, right? I mean if someone want to use DBSOCK, he has to set the env valuable by himself.

**Comment by ericvaandering** [comment]
Yes, exactly. I've tested this and it works just fine, but by default nothing changes.

**Comment by geneguvo** [comment]
It looks fine to me.

**Comment by ticoann** [comment]
Diego, could you merge this?

**Pull request closed without merging**
