### PR TITLE
Small layout style change ...

### PR DESCRIPTION
**Pull request by dinardo**
Small layout style change inline with author style ...

### CODE REVIEW

**Comment by threus** [comment]
@BrunoCoimbra
Can you please merge this?
Thanks,
Tomas for DQM

**Comment by dinardo** [comment]
Hi,
forgive my naive comment, I might be to paranoid, but when do you think that this merging will occur ?
I just would like to avoid that it goes lost ... though I don't even know whether this can actually happen with git :-)

Cheers,
- Mauro.

**Comment by vanbesien** [comment]
Not a very naive comment, in fact.
@BrunoCoimbra will you merge this? Or did we miss the deadline for the feb release?
@dinardo don't worry, since for the online, we manually patch the Online GUI and your patch is actually already deployed and active on the online DQM GUI.

**Comment by BrunoCoimbra** [comment]
Sorry guys, I don't know exactly how, but it seems we've missed this PR.
Unfortunately now it's too late for February but I'll make sure it goes on the next release.

**Pull request merged**
