### PR TITLE
Change plot description of ECAL Pedestal quality plot

### PR DESCRIPTION
**Pull request by abhih1**
This PR changes the plot description of the ECAL pedestal quality plot in the online DQM ECAL workspace and the shifter workspace to include the threshold changes mentioned in this CMSSW PR: https://github.com/cms-sw/cmssw/pull/39941

### CODE REVIEW

**Comment by micsucmed** [comment]
@abhih1 changes have been made in the playback DQM GUI, could you please check if everything looks as expected in: https://cmsweb.cern.ch/dqm/online-playback/

**Comment by abhih1** [comment]
@micsucmed Thanks!  Everything looks good. Please go ahead and deploy.

**Comment by arooshap** [comment]
Hi @abhih1,

This pull request has been merged in the `HG2211e` testbed release. Kindly proceed with the validation.

Thanks :)

**Comment by abhih1** [comment]
Hi @arooshap Thanks! Looks as expected. Please deploy in the production online DQM GUI for current runs.

**Pull request merged**
