### PR TITLE
[DQMGUI] Updates on missing GE21 module plots of GUI of GEM onlineDQM

### PR DESCRIPTION
**Pull request by Dongwoon77**
**PR description:**

- Add on GE21-P-L2, GE21-M-L2 M1~M4 module plots at Common
- Add GE21-P-L2, GE21-M-L2 M1~M4 Lumi-based chamber status
- Add GE21-P-L2, GE21-M-L2 M1~M4 OptoHybrid status
- Add GE21-P-L2, GE21-M-L2 M1~M4  VFAT status (chamber vs. VFAT)

I made a mistake for removed previous PR so write new PR.

Here is the previous PR Link [1]

This PR is related to PRs on cms-sw; see  
https://github.com/cms-sw/cmssw/pull/41915 (to master)  
https://github.com/cms-sw/cmssw/pull/42483 (backport)

[1] https://github.com/dmwm/deployment/pull/1303

### CODE REVIEW

**Comment by arooshap** [comment]
Hi @Dongwoon77,

your changes have been incorporated in HG2402b release and deployed in the testbed VMs. Kindly validate, thanks!

**Comment by Dongwoon77** [comment]
Dear @arooshap.

I'm trying to access of https://cmsweb.cern.ch/dqm/online-test, but I can't check because there is a proxy error.
Is it an known issue? Is it possible to figure out when the test server is back?

**Comment by arooshap** [comment]
Hi @Dongwoon77,

I encountered the same issue today for some reason. I will ask the DQM team if there is any ongoing maintenance. But when I refreshed it, it went away. Could you please retry again?

**Comment by Dongwoon77** [comment]
Dear @arooshap.

I retry to access of https://cmsweb.cern.ch/dqm/online-test and refreshed it, but there is still a proxy error.

So I'll wait until this issue is solved and then will retry this

**Comment by nothingface0** [comment]
@Dongwoon77 Sorry for this, this machine has been taken offline, after our migration to new machines. Is it a machine that you had access to before?

**Comment by nothingface0** [comment]
@Dongwoon77 If you need a PR to be validated, you can either deploy your personal DQMGUI (e.g. on [OpenStack](https://github.com/cms-DQM/dqmgui_prod_deployment/wiki/Deployment-on-OpenStack)), or contact us (the DQM-DC team) for testing it on our playback machine. 

We have deployed your changes on the [playback machine](https://cmsweb.cern.ch/dqm/online-playback) for now. Could you check the results? 

Thanks

**Comment by Dongwoon77** [comment]
Hi @nothingface0 

I checked plots at [playback machine](https://cmsweb.cern.ch/dqm/online-playback) link.

It`s been updated well of missing GE21 module plots.

Thank you!

**Pull request merged**
