### PR TITLE
Update WMStats rules for couch view distribution

### PR DESCRIPTION
**Pull request by amaltaro**
Changes applied on top of: https://github.com/dmwm/deployment/pull/907
Also remove a rewriteRule for a deprecated WMStats view: https://github.com/dmwm/WMCore/issues/9695

Frontend rules for these changes applied to WMCore: https://github.com/dmwm/WMCore/pull/9710

### CODE REVIEW

**Comment by amaltaro** [comment]
https://github.com/dmwm/deployment/pull/907 needs to be merged first. I might have to rebase this one.

**Comment by amaltaro** [comment]
@vkuznet Valentin, can you please review this PR as well? Thanks

**Comment by vkuznet** [comment]
since it is already merged I don't see the point of reviewing it now.

**Comment by amaltaro** [comment]
Yes and now, you review can still prevent a bug from going to production.

**Comment by vkuznet** [comment]
logic of PR is fine. But obviously thing should be checked.

**Pull request merged**
