### PR TITLE
Change to DT Render Plugin 

### PR DESCRIPTION
**Pull request by jfernan2**
for color palette in SegmentOccupancySummary (histo SegmentGlbSummary)

### CODE REVIEW

**Comment by threus** [comment]
@jfernan2 do you plan to add more commits to this PR or we (DQM) can start testing it? I don't see a note in the P5TagCollector, neither an email yet, so I am curious..

**Comment by jfernan2** [comment]
@threus I do not plan to add more commits for the moment and this change only affects DQM Offline, that's why I did not set a note in the P5TagCollector. Thanks!

**Comment by threus** [comment]
ok great then. I will test it for offline locally and if all is fine, I'll ask to merge.

**Comment by threus** [comment]
@BrunoCoimbra @h4d4 , Tests OK. Could you please merge this?
Thanks,
Tomas for DQM

**Comment by threus** [comment]
@h4d4 sorry, please do not merge yet - I see new commits.
@jfernan2 I thought you said no more commits to this PR. We tested it and asked to merge. Could you maybe tell us what are your plans with this PR? Thanks

**Comment by jfernan2** [comment]
@threus I'm very sorry, since it was not merged yet we believed we could still get another minor change in the same PR to not bother you again with a new PR for another small change.
We don't foresee any other change to this PR for sure. Again, the new change only affects to DQM offline.
Thank you very much and apologies for the incovenience.

**Comment by threus** [comment]
@jfernan2 ok thanks for explanation, understood. I will deal with it next week, I take it's not super-urgent (in the view of the coming collisions this weekend).
Next time it's better to open a new PR (except when you find a bug in this PR), because people might get confused. Never mind it being small :)

**Comment by jfernan2** [comment]
Thank you @threus It is not superurgent since it is for DT Offline, but something we need for the DOC3 shift which is being requested for this year data taking.
Thanks!

**Comment by jfernan2** [comment]
Sorry, has this PR been finally merged? Thanks

**Comment by threus** [comment]
hi @jfernan2 , not yet, it's in my todo list, I already started testing it locally, but got some (probably unrelated) crashes.. will conclude soon.
sorry for being late (online being the priority right now)

**Comment by threus** [comment]
@h4d4 @emaszs @jfernan2 I see here the commit https://github.com/dmwm/deployment/pull/477/commits/a66c3562695781168d3bc66ea4412e56860502d4 which is unrelated to this PR and comes from #474 . I have no idea how it could have landed here, could someone please remove it from this PR? Thanks!

**Comment by jfernan2** [comment]
@threus that commit is probably here by mistake from my side, I reverted so that the PR ony includes my modifed file, however I don't know how to remove a commit from a PR. Thanks

**Comment by threus** [comment]
@h4d4 could you please remove  https://github.com/dmwm/deployment/pull/477/commits/a66c3562695781168d3bc66ea4412e56860502d4 from here and then merge this PR?
Thanks,
Tomas for DQM

**Comment by h4d4** [comment]
@threus I removed it  and merged the PR. You can look the last commits for _Commits on May 26, 2017_  on:
https://github.com/dmwm/deployment/commits/master
Regards, Lina

**Comment by threus** [comment]
great, thanks @h4d4 . 
@jfernan2, since your changes are merged, you can close this PR.

**Comment by jfernan2** [comment]
Thanks!

**Comment by jfernan2** [comment]
@h4d4 @threus Sorry to bother you again, but this PR does not seem to show up in DQM offline still, is there any reason?
Thanks

**Comment by vanbesien** [comment]
Read the TWiki.
Especially the part about how the releases work.

Cheers,

Broen

**Pull request closed without merging**
