### PR TITLE
Update SiStripAPVGain PCL style / layout

### PR DESCRIPTION
**Pull request by mmusich**
### Relevant for offline only ###
Title says it all:
   * Taking into account changes done at: https://github.com/cms-sw/cmssw/pull/38234
   * tested locally on a development GUI (`ssh -NL 8060:localhost:8060 <user>@lxplus708.cern.ch` + https://tinyurl.com/24shoasf)

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@mmusich 

Could you please confirm about this PR. Is it ready for production deployment.

**Comment by mmusich** [comment]
@muhammadimranfarooqi is it deployed in a dev instance that I can check?

**Comment by muhammadimranfarooqi** [comment]
@mmusich 
Yes, it is deployed in testbed

**Comment by mmusich** [comment]
@muhammadimranfarooqi looks OK. Thank you.

**Pull request merged**
