### PR TITLE
Pixel plots text fix

### PR DESCRIPTION
**Pull request by enochnotsocool**
1. Fix to the plots titles and description in the layout directory
2. Fix the bin labels plots overlapping with the axis title
3. Added bin label to 1D plot (previously missed)

### CODE REVIEW

**Comment by threus** [comment]
@BrunoCoimbra @h4d4 could you please merge this PR?
Thanks,
Tomas for DQM

**Comment by threus** [comment]
@enochnotsocool wasn't this PR already merged? We already added this PR in production 3 weeks ago. Please close this PR again and start a new one, based on the master branch.

**Comment by enochnotsocool** [comment]
I think don't think everything is merged? In any case I will close this PR and resubmit a new one with the missing updates. 
Thanks

**Comment by threus** [comment]
@enochnotsocool great, thanks! Start from the master branch, then you can add what is missing, based on what is already merged.

**Pull request closed without merging**
