### PR TITLE
fixes bug with token file being required for mkvomsmap

### PR DESCRIPTION
**Pull request by Panos512**

### CODE REVIEW

**Comment by amaltaro** [comment]
@Panos512 Hi Panos, with this patch, another problem arises a few lines below
```
amaltaro@alancc7-cloud1:/data/srv/current $ /data/srv/current/config/frontend/mkvomsmap --key /data/certs/hostkey.pem --cert /data/certs/hostcert.pem -c /data/srv/current/config/frontend/mkgridmap.conf -o /data/srv/state/frontend/etc/voms-gridmap.txt --vo cms --git-token-path /data/srv/HG2010e/auth/frontend/gitlab_token.txt
Reading error at /data/srv/HG2010e/auth/frontend/gitlab_token.txt. Wrong path defined or file doesn't exist.
List of blacklisted DNs couldn't be fetched from GitLab.
Traceback (most recent call last):
  File "/data/srv/current/config/frontend/mkvomsmap", line 147, in <module>
    blacklisted_dns = urllib2.urlopen(gitlab_url).read().split('\n')
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib64/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: 
```

**Comment by Panos512** [comment]
Hi Alan, I believe this is expected behaviour. The script should complete and create the file but without processing the blacklisted entries. We just print the traceback when we handle the exception to know exactly what went wrong with the call to the GitLab API. In that case, the URL is just an empty string because it was never constructed properly since the gitlab_token.txt file was missing.

**Comment by amaltaro** [comment]
How about we check whether `gitlab_url` is set (or not empty) before we try to open that url? There is already this print statement
```
print "Reading error at %s. Wrong path defined or file doesn't exist." % opts.git_token_path
```
so, `if not gitlab_url`, we could simply pass that block of code executing the
```
blacklisted_dns = urllib2.urlopen(gitlab_url).read().split('\n')
```

thus not logging that traceback back to the user.

**Comment by Panos512** [comment]
Yes perfect, I agree. Thanks, @amaltaro I implemented it that way.

**Comment by vkuznet** [comment]
+1

**Comment by amaltaro** [comment]
Still not working btw:
```
amaltaro@alancc7-cloud1:/data/srv/current $ /data/srv/current/config/frontend/mkvomsmap --key /data/certs/hostkey.pem --cert /data/certs/hostcert.pem -c /data/srv/current/config/frontend/mkgridmap.conf -o /data/srv/state/frontend/etc/voms-gridmap.txt --vo cms --git-token-path /data/srv/HG2010e/auth/frontend/gitlab_token.txt
Reading error at /data/srv/HG2010e/auth/frontend/gitlab_token.txt. Wrong path defined or file doesn't exist.
Traceback (most recent call last):
  File "/data/srv/current/config/frontend/mkvomsmap", line 165, in <module>
    if user in blacklisted_dns:
NameError: name 'blacklisted_dns' is not defined
```

**Comment by Panos512** [comment]
Just fixed that : )

**Comment by amaltaro** [comment]
Thanks Panos, it works well now:
```
amaltaro@alancc7-cloud1:/data/srv/current $ /data/srv/current/config/frontend/mkvomsmap --key /data/certs/hostkey.pem --cert /data/certs/hostcert.pem -c /data/srv/current/config/frontend/mkgridmap.conf -o /data/srv/state/frontend/etc/voms-gridmap.txt --vo cms --git-token-path /data/srv/HG2010e/auth/frontend/gitlab_token.txt
Reading error at /data/srv/HG2010e/auth/frontend/gitlab_token.txt. Wrong path defined or file doesn't exist.
amaltaro@alancc7-cloud1:/data/srv/current $
```

**Comment by Panos512** [comment]
Sure, sorry for the trouble

**Pull request merged**
