### PR TITLE
[CMSLITDPG-538] Add all plots with quality tests linked to the reportSummaryMaps to quick collections

### PR DESCRIPTION
**Pull request by stahlleiton**
This PR adds all L1T DQM plots with quality tests linked to the L1T reportSummaryMaps to L1T quick collections. It solves the L1T jira https://its.cern.ch/jira/browse/CMSLITDPG-538

This PR is made on top of the PR dmwm#612

@thomreis

### CODE REVIEW

**Comment by threus** [comment]
@stahlleiton #612 got merged, which creates conflicts in this PR. Could you please rebase it to the master branch? thanks!

**Comment by thomreis** [comment]
Hi @stahlleiton 
if you are rebasing do you think you could also add this one plot to the quickCollection:
https://its.cern.ch/jira/browse/CMSLITDPG-287. Not really worth making a separate PR for just one plot.

**Comment by threus** [comment]
@stahlleiton no, no need to rebase now. I am not sure why there are no conflicts anymore, but there were conflicts when I first checked. Sorry for the noise.

**Comment by threus** [comment]
@h4d4 , Tests are OK. Could you please merge this? Also, thanks for fixing #612.
Thanks,
Tomas for DQM

**Comment by h4d4** [comment]
@threus yw! :)

**Comment by thomreis** [comment]
Hi @stahlleiton 
could it be that you forgot adding plot 70 to the offline workspaces file? The plot is missing in the quickcollection.

**Comment by thomreis** [comment]
I will have to make a new PR to fix a type soon as well. I can add it then. No need to make a separate one just for this.

**Pull request merged**
