### PR TITLE
Redirecting WMCore and ConfDB from K8s FEs to VM backends

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

Could you please review this PR. WMCore and ConfDB will be redirecting to VMs from K8s FEs. Did I miss any WMCore service? Thanks

**Comment by amaltaro** [comment]
I guess I'll need more information on these changes and what the goal is. My first comments/ questions are:
* weren't we supposed to be using vocms0745 for k8s-preprod CouchDB activities? From what I can see, k8s-preprod is accessing the cmsweb-testbed CouchDB database;
* I have the impression I saw an email in the last weeks asking for the deprecation of confdb(?) You might want to check it and decommission that service if possible.
* I'd rather test things first in preprod, before making any changes to the backends map in k8s-prod.

Cc'ing @khurtado and @goughes to follow up on extra discussion

**Comment by muhammadimranfarooqi** [comment]
@amaltaro @khurtado @goughes 

When we are moving WMCOre services to VMs, then there is no point of using vocms0745 then. As we want to run the setup using DNS aliases. 
Regarding ConfDB, we discuss this, we'll keep this running in the VM at the moment.
Surely, these changes will only be applied to preprod at the moment. Production changes will be applied during production upgrade. We have some days to test in the preprod.

**Comment by amaltaro** [comment]
This means that a workqueue pod would try:
1. to access reqmgr2 under cmsweb-k8s-preprod
2. this request would go to the testbed VMs (vocms0132/vocms0731)
3. those VMs would fetch data from "the official" testbed couchdb database/instance
4. workqueue would then create the chunks of work - and write them to the official testbed couchdb instance
5. finally, workqueue would try to update the request status using the cmsweb=testbed reqmgr2 instances.

The same process could be happening from inside cmsweb-testbed (with the workqueue instance in there).
I'm afraid this can't happen. I'm busy with Rucio transition this week and in the next week and I can't follow this up, please rely on Kenyi and Erik for that, it needs to be well thought.

**Comment by muhammadimranfarooqi** [comment]
There will be no pod of any dmwm service in k8s. Every request will be redirected to the VM for any service in dmwm namespace. In this regards, would this PR be OK?

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Could you please review this PR. Thanks

**Comment by vkuznet** [comment]
The changes looks fine to me.

@amaltaro we discussed internally that DMWM stack is largely delayed and there no need to wait until your group will get time to work on k8s validation, i.e. we can move all other services. This means that we can keep DMWM services in VMs for time being until you'll find time to validate everything. With this in mind the changes just reflects that, i.e. the FE will be in k8s while all DMWM services will be redirected to VM BEs.

**Comment by khurtado** [comment]
@muhammadimranfarooqi @vkuznet 
Question: If all requests in cmsweb-k8s-preprod are redirected to VM BEs, how are we supposed to validate the actual cmsweb-k8s-preprod k8s backend services?

**Comment by vkuznet** [comment]
Kenyi, there are two steps here:
- one is to test that we can use k8s FE to redirect all DMWM service back to VM BEs
- once first step complete and we apply it to production, then we switch back k8s testbed to use k8s testbed DMWM service for you to proceed with testing.

**Comment by khurtado** [comment]
@vkuznet , @muhammadimranfarooqi 

Thanks for clarifying, that makes sense. I just had a chat with @amaltaro regarding this. 
If you can confirm us that none of the DMWM backend services would ever get to run from the k8s cluster while we have such backend redirection rules from the FE, then this is good and we can go ahead with the changes. 

Please, note again, with this we mean none of the DMWM/T0-related services (ms-monitor, ms-output, ms-transferor , reqmgr2, reqmon, workqueue, t0reqmon) can run from the k8s cluster. This applies to both preprod and prod cases.

**Comment by vkuznet** [comment]
Kenyi, I rather would like to wait for our meeting on this subject to discuss this plan and then agree how to implement it. This PR only outline a technical details how it can be done.

**Comment by khurtado** [comment]
@vkuznet OK, sounds good.

**Pull request merged**
