### PR TITLE
Adding calo object DE agreement summary plots to the L1TEMU QuickCollection/Shifter

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Adding calo object data to emulator agreement summary plots to the L1TEMU QuickCollection and the shifter collection.
Also, adding the Calo Layer 2 prefix in histogram names for the L1T QuickCollection.
Requires PR #599

### CODE REVIEW

**Comment by vukasinmilosevic** [comment]
Hi @threus, should I close this one and open a new one? The conflict came from something that was not affected by #599 (or maybe I'm missing something).

**Comment by threus** [comment]
I believe the conflict came from using the same commits as in #599. Seems like the only relevant commits here are

**Comment by vukasinmilosevic** [comment]
Hi @threus, yes they are. I will close this one and open a new one

**Comment by threus** [comment]
wait - I have to retract my last comment. I assumed that #599 is already merged, which is not true. Apologies for confusion. Then the conflict is because of something else.

**Comment by vukasinmilosevic** [comment]
No problem. I have an additional message that states that the conflict comes from:
dqmgui/layouts/shift_l1temulator_layout.py

**Pull request merged**
