### PR TITLE
Add local trigger information (theta view) to DT layouts and fix  a minor issue in the Private DT DQM GUI customisation

### PR DESCRIPTION
**Pull request by battibass**
Following the workflow applied for PR #1302, here is an additional **PR** that:

- adds to `dt-layouts.py` more plots, upon request of the DT P5 experts 
- fix a small bug to `dqmgui/server-conf-online.py` making it consistent with the actual private DT DQM online GUI depoloyed in `dqmfu-c2b03-46-01`

Both were tested using the private deployment of the DQM GUI at P5.
I remain at disposal in case further work is needed on the DT community side.

### CODE REVIEW

**Comment by nothingface0** [comment]
@battibass We've deployed on Playback (https://cmsweb.cern.ch/dqm/online-playback), could you check if it's OK?

**Comment by battibass** [comment]
Thank you very much @nothingface0.
I confirm changes are as expected.

**Comment by arooshap** [comment]
The changes have been incorporated in the release `HG2404a`. Let me know if it is okay for production!

Cheers, 
Aroosha

**Comment by syuvivida** [comment]
Hi @arooshap 
   This PR doesn't affect offline DQMGUI so there is no urgency for pushing for production at vocms0738. Thanks!!

**Pull request merged**
