### PR TITLE
Updates on GUI of GEM onlineDQM and offlineDQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
 - Rearrange and add on layouts of GEM onlineDQM and offlineDQM plots
 - Adding GE21

This PR is related to PRs on cms-sw; see  
https://github.com/cms-sw/cmssw/pull/38398 (to master)
https://github.com/cms-sw/cmssw/pull/38499 (backport to CMSSW_12_3_X)

### CODE REVIEW

**Comment by quark2** [comment]
Hi, 

We wish to deploy this update for the collision run tomorrow. Is it possible?

**Comment by muhammadimranfarooqi** [comment]
Hi @quark2 

I have deployed it in the testbed. Please validate. Thanks

**Comment by seungjin-yang** [comment]
Hi @muhammadimranfarooqi, since this PR affects both online and offline DQM GUIs, I will validate the offline one, and @quark2 will do the online DQM GUI. By the way, I tried to upload a DQMIO file to https://cmsweb.cern.ch/dqm/offline-test but got an error (`SSL: CERTIFICATE_VERIFY_FAILED`). I tried it with a new certificate but got the same error. I tried to a file to https://cmsweb-testbed.cern.ch/dqm/offline-test/ but it was the same as before. Also, I've experienced uploading files to the test bed with an existing certificate in the past (https://github.com/dmwm/deployment/pull/1042#issuecomment-810787221). FYI, I followed https://ca.cern.ch/ca/Help/?kbid=024010 to convert .p12 to pem key pair. 


Here are the full logs.
```console
$ DQMIO_FILE=DQM_V0001_R000000001__TwelveMu_Pt-0-200_Eta-1p5-2p2_pythia8_2023__PR1160_Testing_GEM-v1__DQM.root
$ $DQMGUI/current/apps/dqmgui/etc/profile.d/env.sh
$ visDQMUpload https://cmsweb.cern.ch/dqm/offline-test ${DQMIO_FILE}
DQM_V0001_R000000001__TwelveMu_Pt-0-200_Eta-1p5-2p2_pythia8_2023__PR1160_Testing_GEM-v1__DQM.root
Using SSL private key /tmp/x509up_u113501
Using SSL public key /tmp/x509up_u113501
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02739/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-06-26-2300/bin/slc7_amd64_gcc10/visDQMUpload.py", line 157, in <module>
    upload(sys.argv[1],
  File "/cvmfs/cms-ib.cern.ch/nweek-02739/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-06-26-2300/bin/slc7_amd64_gcc10/visDQMUpload.py", line 91, in upload
    result = urllib2.build_opener(HTTPSCertAuthenticate()).open(datareq)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/urllib/request.py", line 528, in _open
    result = self._call_chain(self.handle_open, 'default',
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/cvmfs/cms-ib.cern.ch/nweek-02739/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_X_2022-06-26-2300/bin/slc7_amd64_gcc10/visDQMUpload.py", line 42, in default_open
    return self.do_open(HTTPSCertAuth, req)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
```

```console
$ $ DQMIO_FILE=DQM_V0001_R000000001__TwelveMu_Pt-0-200_Eta-1p5-2p2_pythia8_2023__PR1160_Testing_GEM-v1__DQM.root
$ cd /cvmfs/cms.cern.ch/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_0_pre1/src/
$ cmsenv
$ cd -
$ visDQMUpload.py https://cmsweb.cern.ch/dqm/offline-test ${DQMIO_FILE}
DQM_V0001_R000000001__TwelveMu_Pt-0-200_Eta-1p5-2p2_pythia8_2023__PR1160_Testing_GEM-v1__DQM.root
Using SSL private key /tmp/x509up_u113501
Using SSL public key /tmp/x509up_u113501
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_0_pre1/bin/slc7_amd64_gcc11/visDQMUpload.py", line 157, in <module>
    upload(sys.argv[1],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_0_pre1/bin/slc7_amd64_gcc11/visDQMUpload.py", line 91, in upload
    result = urllib2.build_opener(HTTPSCertAuthenticate()).open(datareq)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/urllib/request.py", line 528, in _open
    result = self._call_chain(self.handle_open, 'default',
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_5_0_pre1/bin/slc7_amd64_gcc11/visDQMUpload.py", line 42, in default_open
    return self.do_open(HTTPSCertAuth, req)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc11/external/python3/3.9.6-31243b7954f759569bb33178ee787cfa/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)>
```

**Comment by muhammadimranfarooqi** [comment]
@quark2 
Please try deleting your old/new certificate and then import new certificate again. Delete history/cookies and then try again

**Comment by seungjin-yang** [comment]
Thanks, @muhammadimranfarooqi!

Do I need to update the certificate in my browser? I can access the testbed site via the web browser but can't upload a file to the testbed using `visDQMUpload` tool. Also, I'm trying to upload a DQMIO file from a remote server, not a local machine. Can I upload a file through a browser?

Also, the validity of a new certificate looks okay.
```console
$ openssl x509 -enddate -noout -in ~/.globus/usercert.pem
notAfter=Aug  8 14:20:57 2023 GMT
```

**Comment by muhammadimranfarooqi** [comment]
@quark2 

If you can access testbed site via browser, then there is no issue with the certificate. I think you may ask help from DQM experts in this case as this issue is related with the application itself.

**Comment by seungjin-yang** [comment]
@muhammadimranfarooqi 

Okay. I just hacked the script (`visDQMUpload`) to upload a file to the GUI site. I confirmed that [OFFLINE DQM GUI](https://cmsweb.cern.ch/dqm/offline-test/start?runnr=1;workspace=GEM;dataset=/TwelveMu_Pt-0-200_Eta-1p5-2p2_pythia8_2023/PR1160_Testing_GEM-v1/DQM) works well as expected. Thanks!



image

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi, 

And also I have checked onlineDQM works well as expected. This PR works currently well on all sides.

image

**Comment by quark2** [comment]
Hi @muhammadimranfarooqi, 

This update should be deployed to the central DQMs, but we found that it's not currently. Could you deploy it?

**Comment by muhammadimranfarooqi** [comment]
Hi @quark2 

The deployment in production servers is scheduled early next week.

**Pull request merged**
