### PR TITLE
Prod and pre-prod rules for ReqMgr2 Microservices

### PR DESCRIPTION
**Pull request by amaltaro**
Added frontend rules for the ReqMgr2 Microservices. As per the deployment, it's enabled in:
* vocms0731 for pre-prod
* vocms0740 for prod

@vkuznet can you please review.
@h4d4 Lina, as we discussed on chat. Since you're going to redeploy testbed soon, it might be worth it to test these changes before merging it.

### CODE REVIEW

**Comment by h4d4** [comment]
@amaltaro I'm going to put it by hand first, I'll ping you to check on the browser side.

**Comment by vkuznet** [comment]
+1

**Comment by amaltaro** [comment]
Lina, can you also add this information to this table: https://cms-http-group.web.cern.ch/cms-http-group/activity.html , mapping those 2 backends to "ReqMgr2 Microservices".
Thanks

**Comment by vkuznet** [comment]
And, please list the port it is using. The port is 8248.

**Comment by h4d4** [comment]
@vkuznet @amaltaro 
The doc was updated: [HTTP group activities](https://cms-http-group.web.cern.ch/cms-http-group/activity.html)

Please let me know in case that you found something there out of the date.

Best Regrds, Lina.

**Comment by amaltaro** [comment]
@h4d4 the documentation doesn't seem to have been updated.

**Pull request merged**
