### PR TITLE
Update of Btag layout and new layout for BTV triggers

### PR DESCRIPTION
**Pull request by marco-link**
Paths in the Btag layout are fixed/updated and some additional plots added.

For the triggers maintained by the BTV group a layout is added.

The changes were previously presented in this BTV meeting:
https://indico.cern.ch/event/916805/#73-update-on-btv-dqm-status

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@marco-link 

Is this PR ready to include in cmsweb new release?

**Comment by marco-link** [comment]
@muhammadimranfarooqi 

Yes, this PR is ready for merging.

**Comment by jfernan2** [comment]
Sorry, was this PR intended for Offline DQM right?
FYI: @ErnestaP

**Comment by marco-link** [comment]
@jfernan2 
Yes, this PR affects the Offline DQM.
It affects the `POG/Btag` workspace and adds layouts under `Trigger/HLT`.

Sorry if this wasn't clear.

**Comment by muhammadimranfarooqi** [comment]
@marco-link 

Please update on this ticket that this PR is ready to deploy in the production. 

https://gitlab.cern.ch/cms-http-group/doc/-/issues/234

Thanks

**Pull request merged**
